<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Открытие-файлов-с-данными-и-изучение-общей-информации" data-toc-modified-id="Открытие-файлов-с-данными-и-изучение-общей-информации-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Открытие файлов с данными и изучение общей информации</a></span><ul class="toc-item"><li><span><a href="#Таблица-005.-Распространенность-злокачественных-новообразований-в-России-в-2011-2021-гг." data-toc-modified-id="Таблица-005.-Распространенность-злокачественных-новообразований-в-России-в-2011-2021-гг.-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Таблица 005. Распространенность злокачественных новообразований в России в 2011-2021 гг.</a></span></li><li><span><a href="#Таблицы-006.-Доля-больных,-состоявших-на-учете-в-онкологических-учреждениях-России-5-лет-и-более-момента-установления-диагноза-злокачественного-новообразования,-от-числа-состоявших-на-учете-на-конец-отчетного-года-в-2011-2021-гг.,-%" data-toc-modified-id="Таблицы-006.-Доля-больных,-состоявших-на-учете-в-онкологических-учреждениях-России-5-лет-и-более-момента-установления-диагноза-злокачественного-новообразования,-от-числа-состоявших-на-учете-на-конец-отчетного-года-в-2011-2021-гг.,-%-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Таблицы 006. Доля больных, состоявших на учете в онкологических учреждениях России 5 лет и более момента установления диагноза злокачественного новообразования, от числа состоявших на учете на конец отчетного года в 2011-2021 гг., %</a></span></li><li><span><a href="#Таблица-007.-Доля-больных,-состоявших-на-учете-в-онкологических-учреждениях-России-5-лет-и-более-с-момента-становления-диагноза-злокачественного-новообразования,-от-числа-состоявших-на-учете-на-конец-отчетного-года--5-лет-назад--в-2011-2021-гг.,-%" data-toc-modified-id="Таблица-007.-Доля-больных,-состоявших-на-учете-в-онкологических-учреждениях-России-5-лет-и-более-с-момента-становления-диагноза-злокачественного-новообразования,-от-числа-состоявших-на-учете-на-конец-отчетного-года--5-лет-назад--в-2011-2021-гг.,-%-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Таблица 007. Доля больных, состоявших на учете в онкологических учреждениях России 5 лет и более с момента становления диагноза злокачественного новообразования, от числа состоявших на учете на конец отчетного года  5 лет назад  в 2011-2021 гг., %</a></span></li><li><span><a href="#Таблица-008.-Индекс-накопления-контингента-больных-со-злокачественными-новообразованиями-различных-нозологических-групп-в-России-в-2011-2021-гг." data-toc-modified-id="Таблица-008.-Индекс-накопления-контингента-больных-со-злокачественными-новообразованиями-различных-нозологических-групп-в-России-в-2011-2021-гг.-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Таблица 008. Индекс накопления контингента больных со злокачественными новообразованиями различных нозологических групп в России в 2011-2021 гг.</a></span></li><li><span><a href="#Таблица-009.-Удельный-вес-больных-с-диагнозом,-подтвержденным-морфологически,-от-числа-больных-с-впервые-в-жизни-установленным-диагнозом-злокачественного-новообразования-в-России-в-2011-2021-гг.," data-toc-modified-id="Таблица-009.-Удельный-вес-больных-с-диагнозом,-подтвержденным-морфологически,-от-числа-больных-с-впервые-в-жизни-установленным-диагнозом-злокачественного-новообразования-в-России-в-2011-2021-гг.,-1.5"><span class="toc-item-num">1.5&nbsp;&nbsp;</span>Таблица 009. Удельный вес больных с диагнозом, подтвержденным морфологически, от числа больных с впервые в жизни установленным диагнозом злокачественного новообразования в России в 2011-2021 гг.,</a></span></li><li><span><a href="#!-Таблица-010.-Удельный-вес-больных-со-злокачественными-новообразованиями,-выявленных-активно,-от-числа-больных-с-впервые-в-жизни-установленным-диагнозом-злокачественного-новообразования-в-России-в-2011-2021-гг.,-%" data-toc-modified-id="!-Таблица-010.-Удельный-вес-больных-со-злокачественными-новообразованиями,-выявленных-активно,-от-числа-больных-с-впервые-в-жизни-установленным-диагнозом-злокачественного-новообразования-в-России-в-2011-2021-гг.,-%-1.6"><span class="toc-item-num">1.6&nbsp;&nbsp;</span>! Таблица 010. Удельный вес больных со злокачественными новообразованиями, выявленных активно, от числа больных с впервые в жизни установленным диагнозом злокачественного новообразования в России в 2011-2021 гг., %</a></span></li><li><span><a href="#Таблица-011.-Показатели-активного-выявления-злокачественных-новообразований-в-России-в-2011-2021-гг." data-toc-modified-id="Таблица-011.-Показатели-активного-выявления-злокачественных-новообразований-в-России-в-2011-2021-гг.-1.7"><span class="toc-item-num">1.7&nbsp;&nbsp;</span>Таблица 011. Показатели активного выявления злокачественных новообразований в России в 2011-2021 гг.</a></span></li><li><span><a href="#Таблица-012.-Показатели-выявление-рака-шейки-матки-в-стадии-in-situ-в-России-в-2011-2021-гг." data-toc-modified-id="Таблица-012.-Показатели-выявление-рака-шейки-матки-в-стадии-in-situ-в-России-в-2011-2021-гг.-1.8"><span class="toc-item-num">1.8&nbsp;&nbsp;</span>Таблица 012. Показатели выявление рака шейки матки в стадии in situ в России в 2011-2021 гг.</a></span></li><li><span><a href="#Таблица-013.-Удельный-вес-злокачественных-новообразований,-выявленных-в-I-II-стадии,-из-числе-впервые-выявленных-злокачественных-новообразований-в-России-в-2011-2021-гг." data-toc-modified-id="Таблица-013.-Удельный-вес-злокачественных-новообразований,-выявленных-в-I-II-стадии,-из-числе-впервые-выявленных-злокачественных-новообразований-в-России-в-2011-2021-гг.-1.9"><span class="toc-item-num">1.9&nbsp;&nbsp;</span>Таблица 013. Удельный вес злокачественных новообразований, выявленных в I-II стадии, из числе впервые выявленных злокачественных новообразований в России в 2011-2021 гг.</a></span></li><li><span><a href="#Таблица-014.-Удельный-вес-злокачественных-новообразований,-выявленных-в-III-стадии,-из-числа-впервые-выявленных-злокачественных-новообразований-в-России-в-2011-2021-гг.,-%" data-toc-modified-id="Таблица-014.-Удельный-вес-злокачественных-новообразований,-выявленных-в-III-стадии,-из-числа-впервые-выявленных-злокачественных-новообразований-в-России-в-2011-2021-гг.,-%-1.10"><span class="toc-item-num">1.10&nbsp;&nbsp;</span>Таблица 014. Удельный вес злокачественных новообразований, выявленных в III стадии, из числа впервые выявленных злокачественных новообразований в России в 2011-2021 гг., %</a></span></li><li><span><a href="#Таблица-015.-Удельный-вес-злокачественных-новообразований,-выявленных-в-запущенной-стадии-(IV-стадия),-из-числа-впервые-выявленных-злокачественных-новообразований-в-России-в-2011-2021-гг.,-%" data-toc-modified-id="Таблица-015.-Удельный-вес-злокачественных-новообразований,-выявленных-в-запущенной-стадии-(IV-стадия),-из-числа-впервые-выявленных-злокачественных-новообразований-в-России-в-2011-2021-гг.,-%-1.11"><span class="toc-item-num">1.11&nbsp;&nbsp;</span>Таблица 015. Удельный вес злокачественных новообразований, выявленных в запущенной стадии (IV стадия), из числа впервые выявленных злокачественных новообразований в России в 2011-2021 гг., %</a></span></li><li><span><a href="#Таблица-016.-Летальность-больных-в-течение-года-с-момента-установления-диагноза-злокачественного-новообразования-(из-числа-больных,-впервые-взятых-на-учет-в-предыдущем-году)-в-России-в-2011-2021-гг.,-%" data-toc-modified-id="Таблица-016.-Летальность-больных-в-течение-года-с-момента-установления-диагноза-злокачественного-новообразования-(из-числа-больных,-впервые-взятых-на-учет-в-предыдущем-году)-в-России-в-2011-2021-гг.,-%-1.12"><span class="toc-item-num">1.12&nbsp;&nbsp;</span>Таблица 016. Летальность больных в течение года с момента установления диагноза злокачественного новообразования (из числа больных, впервые взятых на учет в предыдущем году) в России в 2011-2021 гг., %</a></span></li><li><span><a href="#Таблица-017.-Основные-показатели-состояния-онкологической-помощи-детскому-населению-(0-14-лет)-России-в-2011-2021-гг." data-toc-modified-id="Таблица-017.-Основные-показатели-состояния-онкологической-помощи-детскому-населению-(0-14-лет)-России-в-2011-2021-гг.-1.13"><span class="toc-item-num">1.13&nbsp;&nbsp;</span>Таблица 017. Основные показатели состояния онкологической помощи детскому населению (0-14 лет) России в 2011-2021 гг.</a></span></li><li><span><a href="#Таблица-055.-Сведения-о-злокачественных-новообразованиях,-лечение-которых-не-проводилось-по-причине-отказа-пациента-и-противопоказаний-к-проведению-лечения-в-России-в-2011-2021-гг." data-toc-modified-id="Таблица-055.-Сведения-о-злокачественных-новообразованиях,-лечение-которых-не-проводилось-по-причине-отказа-пациента-и-противопоказаний-к-проведению-лечения-в-России-в-2011-2021-гг.-1.14"><span class="toc-item-num">1.14&nbsp;&nbsp;</span>Таблица 055. Сведения о злокачественных новообразованиях, лечение которых не проводилось по причине отказа пациента и противопоказаний к проведению лечения в России в 2011-2021 гг.</a></span></li><li><span><a href="#Таблица-056.-Сведения-о-лечении-детей-(0-14-лет)-со-злокачественными-новообразованиями-в-России-в-2011-2021-г." data-toc-modified-id="Таблица-056.-Сведения-о-лечении-детей-(0-14-лет)-со-злокачественными-новообразованиями-в-России-в-2011-2021-г.-1.15"><span class="toc-item-num">1.15&nbsp;&nbsp;</span>Таблица 056. Сведения о лечении детей (0-14 лет) со злокачественными новообразованиями в России в 2011-2021 г.</a></span></li></ul></li><li><span><a href="#Объединение-таблиц" data-toc-modified-id="Объединение-таблиц-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Объединение таблиц</a></span><ul class="toc-item"><li><span><a href="#Таблица-1" data-toc-modified-id="Таблица-1-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Таблица 1</a></span></li></ul></li><li><span><a href="#Выводы" data-toc-modified-id="Выводы-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Выводы</a></span></li></ul></div>

Ссылка на дашборд:
https://datalens.yandex.ru/dpzmxrkdj9vo2-dashbord-medicinskih-dannyh

# Предобработка таблиц по онкозаболеваниям для построения дашборда

Дашборд имеет целью визуализацию данных годового отчета главного онколога России. Отчет за 2021 год состоит из таблиц, которые были конвертированы в Excel, которые необходимо обработать, привести в удобный вид, для того, чтобы использовать в дашборде. Дашборд необходим для предоставления возможности анализа предметным специалистам (онкологам и организаторам здравоохранения).

Для обработки предоставлено 15 таблиц:
- От 5-й до 10-й и от 13 до 16 в строках локализации, в колонках годы (2011-2021) Каждая новая таблица содержит определенные (иные) показатели организации онкологической помощи  
- Таблицы 11 и 12 Важные показатели организации онкодиагностики  в динамике за 10 лет (2011-2021)  
- Таблица 17. Важные показатели организации онкодиагностики  в динамике за 10 лет (2011-2021) в возрастной группе от 0 до 14 лет   
- Таблица 55 - Динамика случаев за 10 лет (2011-2021), в которых лечение злокачественного новообразования не проводилось по тем или иным причинам  
- Таблица 56 - Сведения о лечении ЗНО, использованных методиках лечения в динамике за 10 лет (2011 -2021) в возрастной группе от 0 до 14 лет.  

## Открытие файлов с данными и изучение общей информации

Загрузим 15 таблиц, посмотрим общую информацию о них. В таблицах формата Excel есть многоуровневые заголовки. Зная это, после загрузки таблицы переименуем заголовки, чтобы таблица отображалась корректно. Будем поочередно загружать и обрабатывать таблицы.

In [1]:
#открытие библиотек
import pandas as pd
pd.set_option('display.max_colwidth', None)
import re
from datetime import datetime, timedelta
import warnings
warnings.filterwarnings("ignore")

print('Библиотеки загружены корректно!')

Библиотеки загружены корректно!


### Таблица 005. Распространенность злокачественных новообразований в России в 2011-2021 гг.

In [2]:
# загрузка таблицы
table_005 = pd.read_excel('2021_Таблица_005_Состояние_онко_помощи_в_РФ.xlsx', header=[0, 1, 2, 3])
table_005

Таблица 5  \
   Распространенность злокачественных новообразований в России в 2011-2021 гг.\n(численность контингента больных на 100 тыс. населения)   
                                                                                                      Локализация, нозологическая форма   
                                                                                                                     Unnamed: 0_level_3   
0                                                                                                     Все злокачествен. новообразования   
1                                                                                                                                  Губа   
2                                                                                                                           Полость рта   
3                                                                                                                                Глотка   
4                                                                                                                               Пищевод   
5                                                                                                                               Желудок   
6                                                                                                                       Ободочная кишка   
7                                                                                                   Прямая кишка, ректосигм. соед, анус   
8                                                                                                     Печень и внутрипеч. желч. протоки   
9                                                                                                                  Поджелудочная железа   
10                                                                                                                              Гортань   
11                                                                                                               Трахея, бронхи, легкое   
12                                                                                                              Кости и суставные хрящи   
13                                                                                                                        Меланома кожи   
14                                                                                                                Кожа (кроме меланомы)   
15                                                                                                    Соединительная и др. мягкие ткани   
16                                                                                                                      Молочная железа   
17                                                                                                                          Шейка матки   
18                                                                                                                           Тело матки   
19                                                                                                                               Яичник   
20                                                                                                                Предстательная железа   
21                                                                                                                                Почка   
22                                                                                                                       Мочевой пузырь   
23                                                                                                                    Щитовидная железа   
24                                                                                                       Лимфатич. и кроветворная ткань   
25                                                                                             

Удалим последнюю строку с ремаркой. Заменим название столбца '2021*' на '2021'. Приведем таблицу в удобный для анализа вид. Соединим наименование локализации с кодом.

In [3]:
table_005 = table_005.droplevel(0, axis=1) #удаление верхнего уровня индекса
table_005 = table_005.droplevel(0, axis=1)
table_005 = table_005.droplevel(0, axis=1)
table_005.rename(columns = {'Unnamed: 0_level_3':'Локализация, нозологическая форма',\
                            'Unnamed: 1_level_3':'Код МКБ 10', \
                            '2021*' : '2021'}, inplace = True )
# удаление ремарки
table_005 = table_005.drop(index = 25)
table_005 = table_005.reset_index(drop=True)
table_005

Локализация, нозологическая форма Код МКБ 10    2011    2012    2013  \
0     Все злокачествен. новообразования     С00-96  2029.0  2091.9  2159.4   
1                                  Губа        С00    41.9    40.2    37.7   
2                           Полость рта     С01-09    23.1    23.3    24.4   
3                                Глотка     С10-13    10.1    10.2    10.7   
4                               Пищевод        С15     8.2     8.2     8.4   
5                               Желудок        С16    94.1    94.1    94.1   
6                       Ободочная кишка        С18   111.9   116.7   121.4   
7   Прямая кишка, ректосигм. соед, анус     С19-21    87.3    90.4    93.4   
8     Печень и внутрипеч. желч. протоки        С22     4.7     4.6     4.7   
9                  Поджелудочная железа        С25    10.0    10.5    10.8   
10                              Гортань        С32    29.2    29.0    29.4   
11               Трахея, бронхи, легкое     С33,34    86.5    86.6    88.5   
12              Кости и суставные хрящи     С40,41    11.9    11.5    11.1   
13                        Меланома кожи        С43    48.3    50.1    51.8   
14                Кожа (кроме меланомы)        С44   246.0   252.3   258.3   
15    Соединительная и др. мягкие ткани     С47,49    19.0    19.4    19.6   
16                      Молочная железа        С50   366.8   380.5   391.7   
17                          Шейка матки        С53   113.1   115.0   115.9   
18                           Тело матки        С54   143.2   148.4   153.6   
19                               Яичник        С56    64.5    65.9    68.0   
20                Предстательная железа        С61    84.6    93.6   103.8   
21                                Почка        С64    78.5    84.6    90.7   
22                       Мочевой пузырь        С67    58.4    60.8    63.1   
23                    Щитовидная железа        С73    85.9    89.2    93.0   
24       Лимфатич. и кроветворная ткань     С81-96   112.9   117.7   121.2   

      2014    2015    2016    2017    2018    2019    2020    2021  
0   2252.4  2325.2  2399.1  2472.4  2562.3  2676.6  2712.9  2690.5  
1     36.8    34.9    32.9    30.5    29.1    27.5    26.1    22.5  
2     25.2    25.9    26.6    27.2    28.5    29.7    30.8    30.8  
3     11.2    11.5    11.7    11.9    12.3    12.7    13.2    12.8  
4      8.7     8.7     9.2     9.2     9.4     9.8    10.2     9.5  
5     95.0    94.8    95.3    95.3    95.1    96.0    94.9    91.2  
6    127.5   132.9   138.1   142.8   149.6   157.8   161.6   161.0  
7     98.0   101.6   105.4   108.3   111.6   118.1   121.0   121.1  
8      4.9     5.0     5.3     5.6     5.9     6.2     6.7     6.1  
9     11.5    11.8    12.6    13.1    13.5    14.4    15.2    14.1  
10    30.0    30.1    30.3    30.4    30.8    31.1    30.9    29.2  
11    90.4    91.4    93.7    96.1    98.1   100.5    99.0    94.8  
12    11.3    11.3    10.9    10.9    10.8    10.7    11.1    10.4  
13    54.7    56.9    59.2    61.2    64.1    66.9    69.2    70.4  
14   269.3   275.8   279.8   289.0   298.2   310.5   305.8   302.2  
15    20.4    20.8    21.3    21.5    22.3    22.4    23.1    22.4  
16   410.3   425.5   438.2   456.0   471.5   489.8   501.6   509.2  
17   118.4   119.4   121.3   122.2   123.7   126.9   128.4   126.7  
18   160.3   166.0   170.8   175.3   180.5   187.4   191.2   191.6  
19    70.4    71.9    73.8    74.5    76.2    78.7    80.5    80.5  
20   116.1   128.1   138.1   150.0   162.2   176.3   183.8   187.3  
21    96.7   102.5   108.7   114.5   121.1   128.3   131.5   132.8  
22    65.5    68.2    71.2    74.0    77.1    79.9    81.0    80.0  
23    96.9   101.2   105.6   108.9   114.1   120.5   125.3   126.0  
24   126.0   130.5   135.6   139.4   146.0   151.7   153.8   153.3

In [4]:
# составление словаря- код:локализация
dict_005 = pd.Series(table_005['Код МКБ 10'].values,index=table_005['Локализация, нозологическая форма']).to_dict()
dict_005

{'Все злокачествен. новообразования': 'С00-96',
 'Губа': 'С00',
 'Полость рта': 'С01-09',
 'Глотка': 'С10-13',
 'Пищевод': 'С15',
 'Желудок': 'С16',
 'Ободочная кишка': 'С18',
 'Прямая кишка, ректосигм. соед, анус': 'С19-21',
 'Печень и внутрипеч. желч. протоки': 'С22',
 'Поджелудочная железа': 'С25',
 'Гортань': 'С32',
 'Трахея, бронхи, легкое': 'С33,34',
 'Кости и суставные хрящи': 'С40,41',
 'Меланома кожи': 'С43',
 'Кожа (кроме меланомы)': 'С44',
 'Соединительная и др. мягкие ткани': 'С47,49',
 'Молочная железа': 'С50',
 'Шейка матки': 'С53',
 'Тело матки': 'С54',
 'Яичник': 'С56',
 'Предстательная железа': 'С61',
 'Почка': 'С64',
 'Мочевой пузырь': 'С67',
 'Щитовидная железа': 'С73',
 'Лимфатич. и кроветворная ткань': 'С81-96'}

In [5]:
# переворот таблицы
table_005 = table_005.set_index('Локализация, нозологическая форма') #установление индекса
table_005 = table_005.stack().reset_index()

# переимеование столбца
table_005.rename(columns = {'level_1':'Год', 0:'Численность контингента больных на 100 тыс. населения'}, inplace = True)

table_005

Локализация, нозологическая форма         Год  \
0    Все злокачествен. новообразования  Код МКБ 10   
1    Все злокачествен. новообразования        2011   
2    Все злокачествен. новообразования        2012   
3    Все злокачествен. новообразования        2013   
4    Все злокачествен. новообразования        2014   
..                                 ...         ...   
295     Лимфатич. и кроветворная ткань        2017   
296     Лимфатич. и кроветворная ткань        2018   
297     Лимфатич. и кроветворная ткань        2019   
298     Лимфатич. и кроветворная ткань        2020   
299     Лимфатич. и кроветворная ткань        2021   

    Численность контингента больных на 100 тыс. населения  
0                                                  С00-96  
1                                                  2029.0  
2                                                  2091.9  
3                                                  2159.4  
4                                                  2252.4  
..                                                    ...  
295                                                 139.4  
296                                                 146.0  
297                                                 151.7  
298                                                 153.8  
299                                                 153.3  

[300 rows x 3 columns]

In [6]:
# удаление лишних строк
table_005 = table_005[table_005['Год'] != 'Код МКБ 10']
table_005

Локализация, нозологическая форма   Год  \
1    Все злокачествен. новообразования  2011   
2    Все злокачествен. новообразования  2012   
3    Все злокачествен. новообразования  2013   
4    Все злокачествен. новообразования  2014   
5    Все злокачествен. новообразования  2015   
..                                 ...   ...   
295     Лимфатич. и кроветворная ткань  2017   
296     Лимфатич. и кроветворная ткань  2018   
297     Лимфатич. и кроветворная ткань  2019   
298     Лимфатич. и кроветворная ткань  2020   
299     Лимфатич. и кроветворная ткань  2021   

    Численность контингента больных на 100 тыс. населения  
1                                                  2029.0  
2                                                  2091.9  
3                                                  2159.4  
4                                                  2252.4  
5                                                  2325.2  
..                                                    ...  
295                                                 139.4  
296                                                 146.0  
297                                                 151.7  
298                                                 153.8  
299                                                 153.3  

[275 rows x 3 columns]

In [7]:
# вставка столбца с кодом заболевания
table_005["Код МКБ 10"] = table_005["Локализация, нозологическая форма"].map(dict_005) 

# замена значения столбца, чтоб было в едином стиле для удобного дальнейшего объединения
table_005['Локализация, нозологическая форма'] =  table_005['Локализация, нозологическая форма']\
                                                   .str.replace('Все злокачествен. новообразования',\
                                                                'Все злокачественные новообразования')
table_005['Код МКБ 10'] =  table_005['Код МКБ 10'].str.replace('С81-96','C81-96')

table_005

Локализация, нозологическая форма   Год  \
1    Все злокачественные новообразования  2011   
2    Все злокачественные новообразования  2012   
3    Все злокачественные новообразования  2013   
4    Все злокачественные новообразования  2014   
5    Все злокачественные новообразования  2015   
..                                   ...   ...   
295       Лимфатич. и кроветворная ткань  2017   
296       Лимфатич. и кроветворная ткань  2018   
297       Лимфатич. и кроветворная ткань  2019   
298       Лимфатич. и кроветворная ткань  2020   
299       Лимфатич. и кроветворная ткань  2021   

    Численность контингента больных на 100 тыс. населения Код МКБ 10  
1                                                  2029.0     С00-96  
2                                                  2091.9     С00-96  
3                                                  2159.4     С00-96  
4                                                  2252.4     С00-96  
5                                                  2325.2     С00-96  
..                                                    ...        ...  
295                                                 139.4     C81-96  
296                                                 146.0     C81-96  
297                                                 151.7     C81-96  
298                                                 153.8     C81-96  
299                                                 153.3     C81-96  

[275 rows x 4 columns]

In [8]:
table_005.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 275 entries, 1 to 299
Data columns (total 4 columns):
 #   Column                                                 Non-Null Count  Dtype 
---  ------                                                 --------------  ----- 
 0   Локализация, нозологическая форма                      275 non-null    object
 1   Год                                                    275 non-null    object
 2   Численность контингента больных на 100 тыс. населения  275 non-null    object
 3   Код МКБ 10                                             275 non-null    object
dtypes: object(4)
memory usage: 10.7+ KB


Таблица состоит из 275 строк и 4 столбцов. Название колонок удобночитаемы. Пропущенных значений нет. Данные по численности переведем в вещественный тип.
  
Описание данных  
В каждой строке содержатся количество заболеваний по локализации за каждый год.

In [9]:
# перевод типа данных
table_005['Численность контингента больных на 100 тыс. населения'] =table_005['Численность контингента больных на 100 тыс. населения'].astype(float)
table_005['Год'] = table_005['Год'].astype(int)

In [10]:
# сохранение файла в csv
table_005.to_csv(r'C:\Users\Sincerity\Desktop\Проекты\PET- проекты\Дашборд Заболевания\Подготовленные таблицы\table_005.csv')

### Таблицы 006. Доля больных, состоявших на учете в онкологических учреждениях России 5 лет и более момента установления диагноза злокачественного новообразования, от числа состоявших на учете на конец отчетного года в 2011-2021 гг., %

In [11]:
# загрузка данных
table_006 = pd.read_excel('2021_Таблица_006_Состояние_онко_помощи_в_РФ.xlsx', header=[0, 1, 2, 3])
table_006

Таблица 6  \
   Доля больных, состоявших на учете в онкологических учреждениях России 5 лет и более\nс момента установления диагноза злокачественного новообразования, от числа состоявших на учете на конец отчетного года в 2011-2021 гг., %   
                                                                                                                                                                                                Локализация, нозологическая форма   
                                                                                                                                                                                                               Unnamed: 0_level_3   
0                                                                                                                                                                                               Все злокачествен. новообразования   
1                                                                                                                                                                                                                            Губа   
2                                                                                                                                                                                                                     Полость рта   
3                                                                                                                                                                                                                          Глотка   
4                                                                                                                                                                                                                         Пищевод   
5                                                                                                                                                                                                                         Желудок   
6                                                                                                                                                                                                                 Ободочная кишка   
7                                                                                                                                                                                             Прямая кишка, ректосигм. соед, анус   
8                                                                                                                                                                                               Печень и внутрипеч. желч. протоки   
9                                                                                                                                                                                                            Поджелудочная железа   
10                                                                                                                                                                                                                        Гортань   
11                                                                                                                                                                                                         Трахея, бронхи, легкое   
12                                                                                                                                                                                                        Кости и суставные хрящи   
13                                                                                                                                                                                                                  Меланома кожи   
14                                                                                            

Преобразуем таблицу в удобный вид аналогичным способом, то и предыдущую.

In [12]:
table_006 = table_006.droplevel(0, axis=1) #удаление верхнего уровня индекса
table_006 = table_006.droplevel(0, axis=1)
table_006 = table_006.droplevel(0, axis=1)

# переименование столбцов
table_006.rename(columns = {'Unnamed: 0_level_3':'Локализация, нозологическая форма', 'Unnamed: 1_level_3':'Код МКБ 10'}, inplace = True )

# словарь локализация - код
dict_006 = pd.Series(table_006['Код МКБ 10'].values,index=table_006['Локализация, нозологическая форма']).to_dict()

# переворот таблицы
table_006 = table_006.set_index('Локализация, нозологическая форма') #установление индекса
table_006 = table_006.stack().reset_index()

# переименование колонок
table_006.rename(columns = {'level_1':'Год', \
                            0:'Доля больных, состоявших на учете в онкологических учреждениях России 5 лет и более с момента установления диагноза злокачественного новообразования, от числа состоявших на учете на конец отчетного года'}, inplace = True)

# удаление лишних строк
table_006 = table_006[table_006['Год'] != 'Код МКБ 10']

# вставка столбца с кодом заболевания
table_006["Код МКБ 10"] = table_006["Локализация, нозологическая форма"].map(dict_006) 

# замена значения столбца, чтоб было в едином стиле для удобного дальнейшего объединения
table_006['Локализация, нозологическая форма'] =  table_006['Локализация, нозологическая форма']\
                                                   .str.replace('Все злокачествен. новообразования',\
                                                                'Все злокачественные новообразования')

table_006

Локализация, нозологическая форма   Год  \
1    Все злокачественные новообразования  2011   
2    Все злокачественные новообразования  2012   
3    Все злокачественные новообразования  2013   
4    Все злокачественные новообразования  2014   
5    Все злокачественные новообразования  2015   
..                                   ...   ...   
283       Лимфатич. и кроветворная ткань  2017   
284       Лимфатич. и кроветворная ткань  2018   
285       Лимфатич. и кроветворная ткань  2019   
286       Лимфатич. и кроветворная ткань  2020   
287       Лимфатич. и кроветворная ткань  2021   

    Доля больных, состоявших на учете в онкологических учреждениях России 5 лет и более с момента установления диагноза злокачественного новообразования, от числа состоявших на учете на конец отчетного года  \
1                                                                                                                                                                                                         51.3   
2                                                                                                                                                                                                         51.1   
3                                                                                                                                                                                                         51.7   
4                                                                                                                                                                                                         52.4   
5                                                                                                                                                                                                         52.9   
..                                                                                                                                                                                                         ...   
283                                                                                                                                                                                                       58.6   
284                                                                                                                                                                                                       59.1   
285                                                                                                                                                                                                       59.7   
286                                                                                                                                                                                                       61.1   
287                                                                                                                                                                                                       62.4   

    Код МКБ 10  
1       С00-96  
2       С00-96  
3       С00-96  
4       С00-96  
5       С00-96  
..         ...  
283     C81-96  
284     C81-96  
285     C81-96  
286     C81-96  
287     C81-96  

[264 rows x 4 columns]

In [13]:
# информация о файле
table_006.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 264 entries, 1 to 287
Data columns (total 4 columns):
 #   Column                                                                                                                                                                                                      Non-Null Count  Dtype 
---  ------                                                                                                                                                                                                      --------------  ----- 
 0   Локализация, нозологическая форма                                                                                                                                                                           264 non-null    object
 1   Год                                                                                                                                                                                                

Таблица состоит из 264 строки и 4столбцов. Название колонок удобночитаемы. Пропущенных значений нет. Строку со значениями переведем в вещественный тип данных.
  
Описание данных  
В каждой строке указана доля больных, состоявших на учете в онкологических учреждениях России 5 лет и более момента установления диагноза злокачественного новообразования, от числа состоявших на учете на конец отчетного года в 2011-2021 гг.

In [14]:
# перевод типа данных в float
table_006['Доля больных, состоявших на учете в онкологических учреждениях России 5 лет и более с момента установления диагноза злокачественного новообразования, от числа состоявших на учете на конец отчетного года'] = \
table_006['Доля больных, состоявших на учете в онкологических учреждениях России 5 лет и более с момента установления диагноза злокачественного новообразования, от числа состоявших на учете на конец отчетного года'].astype(float)

In [15]:
# сохранение файла в csv
table_006.to_csv(r'C:\Users\Sincerity\Desktop\Проекты\PET- проекты\Дашборд Заболевания\Подготовленные таблицы\table_006.csv')
table_006['Год'] = table_006['Год'].astype(int)

### Таблица 007. Доля больных, состоявших на учете в онкологических учреждениях России 5 лет и более с момента становления диагноза злокачественного новообразования, от числа состоявших на учете на конец отчетного года  5 лет назад  в 2011-2021 гг., %

In [16]:
# загрузка данных
table_007 = pd.read_excel('2021_Таблица_007_Состояние_онко_помощи_в_РФ.xlsx', header=[0, 1, 2, 3])

table_007

Таблица 7  \
   Доля больных, состоявших на учете в онкологических учреждениях России 5 лет и более\nс момента становления диагноза злокачественного новообразования, от числа состоявших на учете на конец отчетного года  5 лет назад  в 2011-2021 гг., %   
                                                                                                                                                                                                             Локализация, нозологическая форма   
                                                                                                                                                                                                                            Unnamed: 0_level_3   
0                                                                                                                                                                     Все злокачественные новообразования (за исключением кожи кроме меланомы)   
1                                                                                                                                                                                                                                         Губа   
2                                                                                                                                                                                                                         Полость рта и глотка   
3                                                                                                                                                                                                                                      Пищевод   
4                                                                                                                                                                                                                                      Желудок   
5                                                                                                                                                                                                                              Ободочная кишка   
6                                                                                                                                                                                              Прямая кишка,\nректосигмоидное соединение, анус   
7                                                                                                                                                                                                                                      Гортань   
8                                                                                                                                                                                                                       Трахея, бронхи, легкое   
9                                                                                                                                                                                                                         Кости и мягкие ткани   
10                                                                                                                                                                                                                               Меланома кожи   
11                                                                                                                                                                                                                             Молочная железа   
12                                                                                                                                                                                                                                 Шейка матки   
13                                                                                                                 

In [17]:
table_007 = table_007.droplevel(0, axis=1) #удаление верхнего уровня индекса
table_007 = table_007.droplevel(0, axis=1)
table_007 = table_007.droplevel(0, axis=1)

# удаление строки с ремаркой
table_007 = table_007.drop(index = 19)
table_007 = table_007.reset_index(drop=True)
table_007

# переименование столбцов
table_007.rename(columns = {'Unnamed: 0_level_3':'Локализация, нозологическая форма', \
                            'Unnamed: 1_level_3':'Код МКБ 10',\
                           '2014*': '2014',\
                           '2015*': '2015',\
                           '2016*': '2016',\
                           '2017*': '2017',\
                           '2018*': '2018'\
                           }, inplace = True )

# словарь локализация - код
dict_007 = pd.Series(table_007['Код МКБ 10'].values,index=table_007['Локализация, нозологическая форма']).to_dict()

# переворот таблицы
table_007 = table_007.set_index('Локализация, нозологическая форма') #установление индекса
table_007 = table_007.stack().reset_index()

# переименование колонок
table_007.rename(columns = {'level_1':'Год', \
                            0:'Доля больных, состоявших на учете в онкологических учреждениях России 5 лет и более с момента становления диагноза злокачественного новообразования, от числа состоявших на учете на конец отчетного года 5 лет назад'}, inplace = True)

# удаление лишних строк
table_007 = table_007[table_007['Год'] != 'Код МКБ 10']

# вставка столбца с кодом заболевания
table_007["Код МКБ 10"] = table_007["Локализация, нозологическая форма"].map(dict_007) 

# замена значения столбца, чтоб было в едином стиле для удобного дальнейшего объединения
table_007['Локализация, нозологическая форма'] =  table_007['Локализация, нозологическая форма']\
                                                   .str.replace('Прямая кишка,\nректосигмоидное соединение, анус',\
                                                                'Прямая кишка, ректосигм. соед, анус')

table_007['Локализация, нозологическая форма'] =  table_007['Локализация, нозологическая форма'].replace('Все злокачественные новообразования (за исключением кожи кроме меланомы)',\
                                                                'Все злокачественные новообразования')

table_007

Локализация, нозологическая форма   Год  \
1    Все злокачественные новообразования  2011   
2    Все злокачественные новообразования  2012   
3    Все злокачественные новообразования  2013   
4    Все злокачественные новообразования  2014   
5    Все злокачественные новообразования  2015   
..                                   ...   ...   
223       Лимфатич. и кроветворная ткань  2017   
224       Лимфатич. и кроветворная ткань  2018   
225       Лимфатич. и кроветворная ткань  2019   
226       Лимфатич. и кроветворная ткань  2020   
227       Лимфатич. и кроветворная ткань  2021   

    Доля больных, состоявших на учете в онкологических учреждениях России 5 лет и более с момента становления диагноза злокачественного новообразования, от числа состоявших на учете на конец отчетного года 5 лет назад  \
1                                                                                                                                                                                                                    64.7   
2                                                                                                                                                                                                                    64.5   
3                                                                                                                                                                                                                    65.5   
4                                                                                                                                                                                                                    66.7   
5                                                                                                                                                                                                                    67.1   
..                                                                                                                                                                                                                    ...   
223                                                                                                                                                                                                                  69.8   
224                                                                                                                                                                                                                  71.6   
225                                                                                                                                                                                                                  72.2   
226                                                                                                                                                                                                                  72.0   
227                                                                                                                                                                                                                  70.5   

    Код МКБ 10  
1       С00-96  
2       С00-96  
3       С00-96  
4       С00-96  
5       С00-96  
..         ...  
223     C81-96  
224     C81-96  
225     C81-96  
226     C81-96  
227     C81-96  

[209 rows x 4 columns]

In [18]:
# информация о файле
table_007.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 209 entries, 1 to 227
Data columns (total 4 columns):
 #   Column                                                                                                                                                                                                                 Non-Null Count  Dtype 
---  ------                                                                                                                                                                                                                 --------------  ----- 
 0   Локализация, нозологическая форма                                                                                                                                                                                      209 non-null    object
 1   Год                                                                                                                                                               

Таблица состоит из 209 строк и 4 столбцов. Название колонок удобночитаемы. Пропущенных значений нет, данные соответствуют типам данных.
  
Описание данных  
В каждой строке указана доля больных, состоявших на учете в онкологических учреждениях России 5 лет и более с момента становления диагноза злокачественного новообразования, от числа состоявших на учете на конец отчетного года 5 лет назад в 2011-2021 гг.

In [19]:
# перевод типа данных в float
table_007['Доля больных, состоявших на учете в онкологических учреждениях России 5 лет и более с момента становления диагноза злокачественного новообразования, от числа состоявших на учете на конец отчетного года 5 лет назад'] = \
    table_007['Доля больных, состоявших на учете в онкологических учреждениях России 5 лет и более с момента становления диагноза злокачественного новообразования, от числа состоявших на учете на конец отчетного года 5 лет назад'].astype(float)

In [20]:
# сохранение файла в csv
table_007.to_csv(r'C:\Users\Sincerity\Desktop\Проекты\PET- проекты\Дашборд Заболевания\Подготовленные таблицы\table_007.csv')
table_007['Год'] = table_007['Год'].astype(int)

### Таблица 008. Индекс накопления контингента больных со злокачественными новообразованиями различных нозологических групп в России в 2011-2021 гг.

In [21]:
# загрузка данных
table_008 = pd.read_excel('2021_Таблица_008_Состояние_онко_помощи_в_РФ.xlsx', header=[0, 1, 2, 3])
table_008

Таблица 8  \
   Индекс накопления контингента больных со злокачественными новообразованиями различных нозологических групп в России в 2011-2021 гг.   
                                                                                                     Локализация, нозологическая форма   
                                                                                                                    Unnamed: 0_level_3   
0                                                                                                    Все злокачествен. новообразования   
1                                                                                                                                 Губа   
2                                                                                                                          Полость рта   
3                                                                                                                               Глотка   
4                                                                                                                              Пищевод   
5                                                                                                                              Желудок   
6                                                                                                                      Ободочная кишка   
7                                                                                                  Прямая кишка, ректосигм. соед, анус   
8                                                                                                    Печень и внутрипеч. желч. протоки   
9                                                                                                                 Поджелудочная железа   
10                                                                                                                             Гортань   
11                                                                                                              Трахея, бронхи, легкое   
12                                                                                                             Кости и суставные хрящи   
13                                                                                                                       Меланома кожи   
14                                                                                                   Соединительная и др. мягкие ткани   
15                                                                                                                     Молочная железа   
16                                                                                                                         Шейка матки   
17                                                                                                                          Тело матки   
18                                                                                                                              Яичник   
19                                                                                                               Предстательная железа   
20                                                                                                                               Почка   
21                                                                                                                      Мочевой пузырь   
22                                                                                                                   Щитовидная железа   
23                                                                                                      Лимфатич. и кроветворная ткань   

                                                                             \
                                                                              
           Код МКБ 10  Годы                                                   
   Unnamed: 1_level_3  

In [22]:
table_008 = table_008.droplevel(0, axis=1) #удаление верхнего уровня индекса
table_008 = table_008.droplevel(0, axis=1)
table_008 = table_008.droplevel(0, axis=1)

# переименование столбцов
table_008.rename(columns = {'Unnamed: 0_level_3':'Локализация, нозологическая форма', \
                            'Unnamed: 1_level_3':'Код МКБ 10',\
                           }, inplace = True )

# словарь локализация - код
dict_008 = pd.Series(table_008['Код МКБ 10'].values,index=table_008['Локализация, нозологическая форма']).to_dict()

# переворот таблицы
table_008 = table_008.set_index('Локализация, нозологическая форма') #установление индекса
table_008 = table_008.stack().reset_index()

# переименование колонок
table_008.rename(columns = {'level_1':'Год', \
                            0:'Индекс накопления контингента больных'}, inplace = True)

# удаление лишних строк
table_008 = table_008[table_008['Год'] != 'Код МКБ 10']

# вставка столбца с кодом заболевания
table_008["Код МКБ 10"] = table_008["Локализация, нозологическая форма"].map(dict_008) 

# замена значения столбца, чтоб было в едином стиле для удобного дальнейшего объединения
table_008['Локализация, нозологическая форма'] =  table_008['Локализация, нозологическая форма']\
                                                   .str.replace('Все злокачествен. новообразования',\
                                                                'Все злокачественные новообразования')

table_008

Локализация, нозологическая форма   Год  \
1    Все злокачественные новообразования  2011   
2    Все злокачественные новообразования  2012   
3    Все злокачественные новообразования  2013   
4    Все злокачественные новообразования  2014   
5    Все злокачественные новообразования  2015   
..                                   ...   ...   
283       Лимфатич. и кроветворная ткань  2017   
284       Лимфатич. и кроветворная ткань  2018   
285       Лимфатич. и кроветворная ткань  2019   
286       Лимфатич. и кроветворная ткань  2020   
287       Лимфатич. и кроветворная ткань  2021   

    Индекс накопления контингента больных Код МКБ 10  
1                                     6.0     С00-96  
2                                     6.2     С00-96  
3                                     6.4     С00-96  
4                                     6.5     С00-96  
5                                     6.5     С00-96  
..                                    ...        ...  
283                                   8.0     C81-96  
284                                   8.3     C81-96  
285                                   8.3     C81-96  
286                                   9.5     C81-96  
287                                   9.9     C81-96  

[264 rows x 4 columns]

In [23]:
# информация о файле
table_008.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 264 entries, 1 to 287
Data columns (total 4 columns):
 #   Column                                 Non-Null Count  Dtype 
---  ------                                 --------------  ----- 
 0   Локализация, нозологическая форма      264 non-null    object
 1   Год                                    264 non-null    object
 2   Индекс накопления контингента больных  264 non-null    object
 3   Код МКБ 10                             264 non-null    object
dtypes: object(4)
memory usage: 10.3+ KB


Таблица состоит из 264 строки и 4 столбцов. Название колонок удобночитаемы. Пропущенных значений нет. Тип данных в колонке 2 необхоимо поменять на вещественный.  

Описание данных  
В каждой строке указана индекс накопления контингента больных со злокачественными новообразованиями различных нозологических групп в России в 2011-2021 гг.

In [24]:
# перевод типа данных в float
table_008['Индекс накопления контингента больных'] = \
    table_008['Индекс накопления контингента больных'].astype(float)

In [25]:
# сохранение файла в csv
table_008.to_csv(r'C:\Users\Sincerity\Desktop\Проекты\PET- проекты\Дашборд Заболевания\Подготовленные таблицы\table_008.csv')
table_008['Год'] = table_008['Год'].astype(int)

### Таблица 009. Удельный вес больных с диагнозом, подтвержденным морфологически, от числа больных с впервые в жизни установленным диагнозом злокачественного новообразования в России в 2011-2021 гг., 

In [26]:
table_009 = pd.read_excel('2021_Таблица_009_Состояние_онко_помощи_в_РФ.xlsx', header=[0, 1, 2, 3])
table_009

Таблица 9  \
   Удельный вес больных с диагнозом, подтвержденным морфологически, от числа больных с впервые в жизни установленным диагнозом злокачественного новообразования в России в 2011-2021 гг., %   
                                                                                                                                                          Локализация, нозологическая форма   
                                                                                                                                                                         Unnamed: 0_level_3   
0                                                                                                                                                               Все злокач. новообразования   
1                                                                                                                                                                                      Губа   
2                                                                                                                                                                               Полость рта   
3                                                                                                                                                                                    Глотка   
4                                                                                                                                                                                   Пищевод   
5                                                                                                                                                                                   Желудок   
6                                                                                                                                                                           Ободочная кишка   
7                                                                                                                                                       Прямая кишка, ректосигм. соед, анус   
8                                                                                                                                                           Печень и внутрипеч. желч. прот.   
9                                                                                                                                                                      Поджелудочная железа   
10                                                                                                                                                                                  Гортань   
11                                                                                                                                                                   Трахея, бронхи, легкое   
12                                                                                                                                                                  Кости и суставные хрящи   
13                                                                                                                                                                            Меланома кожи   
14                                                                                                                                                                    Кожа (кроме меланомы)   
15                                                                                                                                                        Соединительная и др. мягкие ткани   
16                                                                                                                                                                          Молочная железа   
17                                                                                                                                                                     

In [27]:
table_009 = table_009.droplevel(0, axis=1) #удаление верхнего уровня индекса
table_009 = table_009.droplevel(0, axis=1)
table_009 = table_009.droplevel(0, axis=1)

# переименование столбцов
table_009.rename(columns = {'Unnamed: 0_level_3':'Локализация, нозологическая форма', \
                            'Unnamed: 1_level_3':'Код МКБ 10',\
                           }, inplace = True )

# словарь локализация - код
dict_009 = pd.Series(table_009['Код МКБ 10'].values,index=table_009['Локализация, нозологическая форма']).to_dict()

# переворот таблицы
table_009 = table_009.set_index('Локализация, нозологическая форма') #установление индекса
table_009 = table_009.stack().reset_index()

# переименование колонок
table_009.rename(columns = {'level_1':'Год', \
                            0:'Удельный вес больных с диагнозом, подтвержденным морфологически'}, inplace = True)

# удаление лишних строк
table_009 = table_009[table_009['Год'] != 'Код МКБ 10']

# вставка столбца с кодом заболевания
table_009["Код МКБ 10"] = table_009["Локализация, нозологическая форма"].map(dict_009) 
table_009

# замена значения столбца, чтоб было в едином стиле для удобного дальнейшего объединения
table_009['Локализация, нозологическая форма'] =  table_009['Локализация, нозологическая форма']\
                                                   .str.replace('Все злокач. новообразования',\
                                                                'Все злокачественные новообразования')
table_009

Локализация, нозологическая форма   Год  \
1    Все злокачественные новообразования  2011   
2    Все злокачественные новообразования  2012   
3    Все злокачественные новообразования  2013   
4    Все злокачественные новообразования  2014   
5    Все злокачественные новообразования  2015   
..                                   ...   ...   
295       Лимфатич. и кроветворная ткань  2017   
296       Лимфатич. и кроветворная ткань  2018   
297       Лимфатич. и кроветворная ткань  2019   
298       Лимфатич. и кроветворная ткань  2020   
299       Лимфатич. и кроветворная ткань  2021   

    Удельный вес больных с диагнозом, подтвержденным морфологически Код МКБ 10  
1                                                              85.8     С00-96  
2                                                              86.7     С00-96  
3                                                              87.7     С00-96  
4                                                              88.8     С00-96  
5                                                              90.4     С00-96  
..                                                              ...        ...  
295                                                           100.0     C81-96  
296                                                           100.0     C81-96  
297                                                           100.0     C81-96  
298                                                           100.0     C81-96  
299                                                           100.0     C81-96  

[275 rows x 4 columns]

In [28]:
# информация о файле
table_009.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 275 entries, 1 to 299
Data columns (total 4 columns):
 #   Column                                                           Non-Null Count  Dtype 
---  ------                                                           --------------  ----- 
 0   Локализация, нозологическая форма                                275 non-null    object
 1   Год                                                              275 non-null    object
 2   Удельный вес больных с диагнозом, подтвержденным морфологически  275 non-null    object
 3   Код МКБ 10                                                       275 non-null    object
dtypes: object(4)
memory usage: 10.7+ KB


Таблица состоит из 275 строк и 4 столбца. Название колонок удобночитаемы. Пропущенных значений нет, один тип данных необъодимо перевести в вещественный.  

Описание данных  
В каждой строке указан удельный вес больных с диагнозом, подтвержденным морфологически, от числа больных с впервые в жизни установленным диагнозом злокачественного новообразования в России в 2011-2021 гг.

In [29]:
# перевод типа данных в float
table_009['Удельный вес больных с диагнозом, подтвержденным морфологически'] = \
    table_009['Удельный вес больных с диагнозом, подтвержденным морфологически'].astype(float)

In [30]:
# сохранение файла в csv
table_009.to_csv(r'C:\Users\Sincerity\Desktop\Проекты\PET- проекты\Дашборд Заболевания\Подготовленные таблицы\table_009.csv')
table_009['Год'] = table_009['Год'].astype(int)

### ! Таблица 010. Удельный вес больных со злокачественными новообразованиями, выявленных активно, от числа больных с впервые в жизни установленным диагнозом злокачественного новообразования в России в 2011-2021 гг., %

In [31]:
table_010 = pd.read_excel('2021_Таблица_010_Состояние_онко_помощи_в_РФ.xlsx', header=[0, 1, 2, 3])
table_010

Таблица 10  \
   Удельный вес больных со злокачественными новообразованиями, выявленных активно, от числа больных с впервые в жизни установленным диагнозом злокачественного новообразования в России в 2011-2021 гг., %   
                                                                                                                                                                         Локализация, нозологическая форма   
                                                                                                                                                                                        Unnamed: 0_level_3   
0                                                                                                                                                                              Все злокач. новообразования   
1                                                                                                                                                                                                     Губа   
2                                                                                                                                                                                              Полость рта   
3                                                                                                                                                                                                   Глотка   
4                                                                                                                                                                                                  Пищевод   
5                                                                                                                                                                                                  Желудок   
6                                                                                                                                                                                          Ободочная кишка   
7                                                                                                                                                                      Прямая кишка, ректосигм. соед, анус   
8                                                                                                                                                                        Печень и внутрипеч. желч. протоки   
9                                                                                                                                                                                     Поджелудочная железа   
10                                                                                                                                                                                                 Гортань   
11                                                                                                                                                                                  Трахея, бронхи, легкое   
12                                                                                                                                                                                 Кости и суставные хрящи   
13                                                                                                                                                                                           Меланома кожи   
14                                                                                                                                                                                   Кожа (кроме меланомы)   
15                                                                                                                                                                       Соединительная и др. мягкие ткани   
16                                                                      

In [32]:
table_010 = table_010.droplevel(0, axis=1) #удаление верхнего уровня индекса
table_010 = table_010.droplevel(0, axis=1)
table_010 = table_010.droplevel(0, axis=1)

# переименование столбцов
table_010.rename(columns = {'Unnamed: 0_level_3':'Локализация, нозологическая форма', \
                            'Unnamed: 1_level_3':'Код МКБ 10',\
                           }, inplace = True )

# словарь локализация - код
dict_010 = pd.Series(table_010['Код МКБ 10'].values,index=table_010['Локализация, нозологическая форма']).to_dict()

# переворот таблицы
table_010 = table_010.set_index('Локализация, нозологическая форма') #установление индекса
table_010 = table_010.stack().reset_index()

# переименование колонок
table_010.rename(columns = {'level_1':'Год', \
                            0:'Удельный вес больных со злокачественными новообразованиями, выявленных активно'}, inplace = True)

# удаление лишних строк
table_010 = table_010[table_010['Год'] != 'Код МКБ 10']

# вставка столбца с кодом заболевания
table_010["Код МКБ 10"] = table_010["Локализация, нозологическая форма"].map(dict_010) 

# замена значения столбца, чтоб было в едином стиле для удобного дальнейшего объединения
table_010['Локализация, нозологическая форма'] =  table_010['Локализация, нозологическая форма']\
                                                   .str.replace('Все злокач. новообразования',\
                                                                'Все злокачественные новообразования')
table_010

Локализация, нозологическая форма   Год  \
1    Все злокачественные новообразования  2011   
2    Все злокачественные новообразования  2012   
3    Все злокачественные новообразования  2013   
4    Все злокачественные новообразования  2014   
5    Все злокачественные новообразования  2015   
..                                   ...   ...   
295       Лимфатич. и кроветворная ткань  2017   
296       Лимфатич. и кроветворная ткань  2018   
297       Лимфатич. и кроветворная ткань  2019   
298       Лимфатич. и кроветворная ткань  2020   
299       Лимфатич. и кроветворная ткань  2021   

    Удельный вес больных со злокачественными новообразованиями, выявленных активно  \
1                                                                             14.9   
2                                                                             15.6   
3                                                                             17.3   
4                                                                             18.7   
5                                                                             21.0   
..                                                                             ...   
295                                                                            9.6   
296                                                                           10.1   
297                                                                           10.9   
298                                                                            8.0   
299                                                                            8.3   

    Код МКБ 10  
1       С00-96  
2       С00-96  
3       С00-96  
4       С00-96  
5       С00-96  
..         ...  
295     C81-96  
296     C81-96  
297     C81-96  
298     C81-96  
299     C81-96  

[275 rows x 4 columns]

In [33]:
table_010.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 275 entries, 1 to 299
Data columns (total 4 columns):
 #   Column                                                                          Non-Null Count  Dtype 
---  ------                                                                          --------------  ----- 
 0   Локализация, нозологическая форма                                               275 non-null    object
 1   Год                                                                             275 non-null    object
 2   Удельный вес больных со злокачественными новообразованиями, выявленных активно  275 non-null    object
 3   Код МКБ 10                                                                      275 non-null    object
dtypes: object(4)
memory usage: 10.7+ KB


Таблица состоит из 275 строк и 4 столбца. Название колонок удобночитаемы. Пропущенных значений нет, один тип данных необъодимо перевести в вещественный.  

Описание данных  
В каждой строке указан удельный вес больных со злокачественными новообразованиями, выявленных активно, от числа больных с впервые в жизни установленным диагнозом злокачественного новообразования в России в 2011-2021 гг.,

In [34]:
# перевод типа данных в float
table_010['Удельный вес больных со злокачественными новообразованиями, выявленных активно'] = \
    table_010['Удельный вес больных со злокачественными новообразованиями, выявленных активно'].astype(float)

In [35]:
# сохранение файла в csv
table_010.to_csv(r'C:\Users\Sincerity\Desktop\Проекты\PET- проекты\Дашборд Заболевания\Подготовленные таблицы\table_010.csv')
table_010['Год'] = table_010['Год'].astype(int)

### Таблица 011. Показатели активного выявления злокачественных новообразований в России в 2011-2021 гг.

In [36]:
table_011 = pd.read_excel('2021_Таблица_011_Состояние_онко_помощи_в_РФ.xlsx', header=[0, 1, 2])
table_011

Показатели активного выявления злокачественных новообразований в России в 2011-2021 гг.  \
                                                                                                                                                Показатели   
                                                                                                                                        Unnamed: 0_level_2   
0                                       Доля больных с I-II стадией заболевания, выяв- ленных активно, от числа всех больных с I-II стадией заболевания, %   
1                                          Доля больных с I-II стадией заболевания, выяв- ленных активно, от общего числа больных, вы- явленных активно, %   
2  Доля больных с ЗНО визуальных локализаций от числа больных с впервые в жизни установ- ленным диагнозом, выявленных активно в I-II стадии заболевания, %   

  Таблица 11                                                              
        Годы                                                              
        2011  2012  2013  2014  2015  2016  2017  2018  2019  2020  2021  
0       19.2  21.3  22.4  25.0  27.0  29.5  32.5  34.5  34.3  30.8  29.4  
1       67.2  73.1  69.9  74.2  74.0  77.5  76.2  77.9  78.7  77.9  77.8  
2       64.8  63.8  64.7  64.6  64.4  64.3  64.1  63.2  63.1  61.8  62.8

In [37]:
table_011_2v = table_011.droplevel(0, axis=1) #удаление верхнего уровня индекса
table_011_2v = table_011_2v.droplevel(0, axis=1)

# переименование столбцов
table_011_2v.rename(columns = {'Unnamed: 0_level_2':'Наименование показателя'}, inplace = True )

# переворот таблицы
table_011_2v = table_011_2v.set_index('Наименование показателя') #установление индекса
table_011_2v = table_011_2v.T
table_011_2v

Наименование показателя  Доля больных с I-II стадией заболевания, выяв- ленных активно, от числа всех больных с I-II стадией заболевания, %  \
2011                                                                                                                                   19.2   
2012                                                                                                                                   21.3   
2013                                                                                                                                   22.4   
2014                                                                                                                                   25.0   
2015                                                                                                                                   27.0   
2016                                                                                                                                   29.5   
2017                                                                                                                                   32.5   
2018                                                                                                                                   34.5   
2019                                                                                                                                   34.3   
2020                                                                                                                                   30.8   
2021                                                                                                                                   29.4   

Наименование показателя  Доля больных с I-II стадией заболевания, выяв- ленных активно, от общего числа больных, вы- явленных активно, %  \
2011                                                                                                                                67.2   
2012                                                                                                                                73.1   
2013                                                                                                                                69.9   
2014                                                                                                                                74.2   
2015                                                                                                                                74.0   
2016                                                                                                                                77.5   
2017                                                                                                                                76.2   
2018                                                                                                                                77.9   
2019                                                                                                                                78.7   
2020                                                                                                                                77.9   
2021                                                                                                                                77.8   

Наименование показателя  Доля больных с ЗНО визуальных локализаций от числа больных с впервые в жизни установ- ленным диагнозом, выявленных активно в I-II стадии заболевания, %  
2011                                                                                                                                                                        64.8  
2012                                                                                                                                                                        63.8  
2013                                                             

In [38]:
# информация о файле
table_011_2v.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11 entries, 2011 to 2021
Data columns (total 3 columns):
 #   Column                                                                                                                                                   Non-Null Count  Dtype  
---  ------                                                                                                                                                   --------------  -----  
 0   Доля больных с I-II стадией заболевания, выяв- ленных активно, от числа всех больных с I-II стадией заболевания, %                                       11 non-null     float64
 1   Доля больных с I-II стадией заболевания, выяв- ленных активно, от общего числа больных, вы- явленных активно, %                                          11 non-null     float64
 2   Доля больных с ЗНО визуальных локализаций от числа больных с впервые в жизни установ- ленным диагнозом, выявленных активно в I-II стадии заболевания, %  11 non-null 

Таблица состоит из 11 строки и 3 столбцв. Название колонок удобночитаемы. Пропущенных значений нет. необходимо изменить тип данных на числовой в колонке 2.
  
Описание данных  
В каждой строке стоят показатели активного выявления злокачественных новообразований в России в 2011-2021 гг.

In [39]:
table_011_2v.to_csv(r'C:\Users\Sincerity\Desktop\Проекты\PET- проекты\Дашборд Заболевания\Подготовленные таблицы\table_011_2v.csv')

### Таблица 012. Показатели выявление рака шейки матки в стадии in situ в России в 2011-2021 гг.	

In [40]:
table_012 = pd.read_excel('2021_Таблица_012_Состояние_онко_помощи_в_РФ.xlsx', header=[0, 1, 2])
table_012

Выявление рака шейки матки в стадии in situ в России в 2011-2021 гг.  \
                                                            Показатели   
                                                    Unnamed: 0_level_2   
0    Абсолютное число ЗНО шейки матки (С53) (без выявленных посмертно)   
1          Абсолютное число новообразований in situ\nшейки матки (D06)   
2                                         на 100 ЗНО шейки матки (С53)   

  Таблица 12                                                                 \
        Годы                                                                  
        2011     2012     2013     2014     2015     2016     2017     2018   
0    14617.0  14865.0  15236.0  15840.0  16439.0  16917.0  17303.0  17505.0   
1     3144.0   3585.0   4248.0   4418.0   4637.0   4318.0   4435.0   4490.0   
2       21.3     24.1     27.9     27.9     28.2     25.5     25.6     25.3   

                              
                              
      2019     2020     2021  
0  17221.0  15172.0  15010.0  
1   4964.0   4781.0   5159.0  
2     28.4     31.5     34.4

In [41]:
table_012_2v = table_012.droplevel(0, axis=1) #удаление верхнего уровня индекса
table_012_2v = table_012_2v.droplevel(0, axis=1)

# переименование столбцов
table_012_2v.rename(columns = {'Unnamed: 0_level_2':'Наименование показателя'}, inplace = True)


# переворот таблицы
table_012_2v = table_012_2v.set_index('Наименование показателя') #установление индекса
table_012_2v = table_012_2v.T
table_012_2v

Наименование показателя  Абсолютное число ЗНО шейки матки (С53) (без выявленных посмертно)  \
2011                                                                               14617.0   
2012                                                                               14865.0   
2013                                                                               15236.0   
2014                                                                               15840.0   
2015                                                                               16439.0   
2016                                                                               16917.0   
2017                                                                               17303.0   
2018                                                                               17505.0   
2019                                                                               17221.0   
2020                                                                               15172.0   
2021                                                                               15010.0   

Наименование показателя  Абсолютное число новообразований in situ\nшейки матки (D06)  \
2011                                                                          3144.0   
2012                                                                          3585.0   
2013                                                                          4248.0   
2014                                                                          4418.0   
2015                                                                          4637.0   
2016                                                                          4318.0   
2017                                                                          4435.0   
2018                                                                          4490.0   
2019                                                                          4964.0   
2020                                                                          4781.0   
2021                                                                          5159.0   

Наименование показателя  на 100 ЗНО шейки матки (С53)  
2011                                             21.3  
2012                                             24.1  
2013                                             27.9  
2014                                             27.9  
2015                                             28.2  
2016                                             25.5  
2017                                             25.6  
2018                                             25.3  
2019                                             28.4  
2020                                             31.5  
2021                                             34.4

In [42]:
# информация о файле
table_012_2v.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11 entries, 2011 to 2021
Data columns (total 3 columns):
 #   Column                                                             Non-Null Count  Dtype  
---  ------                                                             --------------  -----  
 0   Абсолютное число ЗНО шейки матки (С53) (без выявленных посмертно)  11 non-null     float64
 1   Абсолютное число новообразований in situ
шейки матки (D06)         11 non-null     float64
 2   на 100 ЗНО шейки матки (С53)                                       11 non-null     float64
dtypes: float64(3)
memory usage: 352.0+ bytes


Таблица состоит из 3 строк и 12 столбцов. Название колонок удобночитаемы. Пропущенных значений нет, данные соответствуют типам данных.
  
Описание данных  
В каждой строке указаны показатели выявление рака шейки матки в начальной стадии в России в 2011-2021 гг.

In [43]:
table_012_2v.to_csv(r'C:\Users\Sincerity\Desktop\Проекты\PET- проекты\Дашборд Заболевания\Подготовленные таблицы\table_012_2v.csv')

### Таблица 013. Удельный вес злокачественных новообразований, выявленных в I-II стадии, из числе впервые выявленных злокачественных новообразований в России в 2011-2021 гг.

In [44]:
table_013 = pd.read_excel('2021_Таблица_013_Состояние_онко_помощи_в_РФ.xlsx', header=[0, 1, 2, 3])
table_013

Таблица 13  \
   Удельный вес злокачественных новообразований, выявленных в I-II стадии, из числе впервые выявленных злокачественных новообразований в России в 2011-2021 гг., %   
                                                                                                                                 Локализация, нозологическая форма   
                                                                                                                                                Unnamed: 0_level_3   
0                                                                                                                                      Все злокач. новообразования   
1                                                                                                                                                             Губа   
2                                                                                                                                                      Полость рта   
3                                                                                                                                                           Глотка   
4                                                                                                                                                          Пищевод   
5                                                                                                                                                          Желудок   
6                                                                                                                                                  Ободочная кишка   
7                                                                                                                              Прямая кишка, ректосигм. соед, анус   
8                                                                                                                                  Печень и внутрипеч. желч. прот.   
9                                                                                                                                             Поджелудочная железа   
10                                                                                                                                                         Гортань   
11                                                                                                                                          Трахея, бронхи, легкое   
12                                                                                                                                         Кости и суставные хрящи   
13                                                                                                                                                   Меланома кожи   
14                                                                                                                                           Кожа (кроме меланомы)   
15                                                                                                                                    Соединит. и др. мягкие ткани   
16                                                                                                                                                 Молочная железа   
17                                                                                                                                                     Шейка матки   
18                                                                                                                                                      Тело матки   
19                                                                                                                                                          Яичник   
20                                                                                                                                           Предстательная железа   
21

In [45]:
table_013 = table_013.droplevel(0, axis=1) #удаление верхнего уровня индекса
table_013 = table_013.droplevel(0, axis=1)
table_013 = table_013.droplevel(0, axis=1)

# переименование столбцов
table_013.rename(columns = {'Unnamed: 0_level_3':'Локализация, нозологическая форма', \
                            'Unnamed: 1_level_3':'Код МКБ 10',\
                           }, inplace = True )

# словарь локализация - код
dict_013 = pd.Series(table_013['Код МКБ 10'].values,index=table_013['Локализация, нозологическая форма']).to_dict()

# переворот таблицы
table_013 = table_013.set_index('Локализация, нозологическая форма') #установление индекса
table_013 = table_013.stack().reset_index()

# переименование колонок
table_013.rename(columns = {'level_1':'Год', \
                            0:'Удельный вес злокачественных новообразований, выявленных в I-II стадии, из числе впервые выявленных злокачественных новообразований'}, inplace = True)

# удаление лишних строк
table_013 = table_013[table_013['Год'] != 'Код МКБ 10']

# вставка столбца с кодом заболевания
table_013["Код МКБ 10"] = table_013["Локализация, нозологическая форма"].map(dict_013) 

# замена значения столбца, чтоб было в едином стиле для удобного дальнейшего объединения
table_013['Локализация, нозологическая форма'] =  table_013['Локализация, нозологическая форма']\
                                                   .str.replace('Соединит. и др. мягкие ткани', \
                                                                'Соединительная и др. мягкие ткани')

# замена значения столбца, чтоб было в едином стиле для удобного дальнейшего объединения
table_013['Локализация, нозологическая форма'] =  table_013['Локализация, нозологическая форма']\
                                                   .str.replace('Все злокач. новообразования',\
                                                                'Все злокачественные новообразования')

table_013

Локализация, нозологическая форма   Год  \
1    Все злокачественные новообразования  2011   
2    Все злокачественные новообразования  2012   
3    Все злокачественные новообразования  2013   
4    Все злокачественные новообразования  2014   
5    Все злокачественные новообразования  2015   
..                                   ...   ...   
271                       Мочевой пузырь  2017   
272                       Мочевой пузырь  2018   
273                       Мочевой пузырь  2019   
274                       Мочевой пузырь  2020   
275                       Мочевой пузырь  2021   

    Удельный вес злокачественных новообразований, выявленных в I-II стадии, из числе впервые выявленных злокачественных новообразований  \
1                                                                                                                                  49.7   
2                                                                                                                                  50.5   
3                                                                                                                                  50.8   
4                                                                                                                                  52.0   
5                                                                                                                                  53.7   
..                                                                                                                                  ...   
271                                                                                                                                75.0   
272                                                                                                                                76.3   
273                                                                                                                                78.0   
274                                                                                                                                77.3   
275                                                                                                                                78.5   

    Код МКБ 10  
1       С00-96  
2       С00-96  
3       С00-96  
4       С00-96  
5       С00-96  
..         ...  
271        С67  
272        С67  
273        С67  
274        С67  
275        С67  

[253 rows x 4 columns]

In [46]:
# информация о файле
table_013.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 253 entries, 1 to 275
Data columns (total 4 columns):
 #   Column                                                                                                                               Non-Null Count  Dtype 
---  ------                                                                                                                               --------------  ----- 
 0   Локализация, нозологическая форма                                                                                                    253 non-null    object
 1   Год                                                                                                                                  253 non-null    object
 2   Удельный вес злокачественных новообразований, выявленных в I-II стадии, из числе впервые выявленных злокачественных новообразований  253 non-null    object
 3   Код МКБ 10                                                                            

Таблица состоит из 253 строк и 4 столбца. Название колонок удобночитаемы. Пропущенных значений нет, некоторые типы данных надо поменять на нужные.  

Описание данных  
В каждой строке указан Удельный вес злокачественных новообразований, выявленных в I-II стадии, из числе впервые выявленных злокачественных новообразований в России в 2011-2021 гг.

In [47]:
# перевод типа данных в float
table_013['Удельный вес злокачественных новообразований, выявленных в I-II стадии, из числе впервые выявленных злокачественных новообразований'] = \
    table_013['Удельный вес злокачественных новообразований, выявленных в I-II стадии, из числе впервые выявленных злокачественных новообразований'].astype(float)

In [48]:
# сохранение файла в csv
table_013.to_csv(r'C:\Users\Sincerity\Desktop\Проекты\PET- проекты\Дашборд Заболевания\Подготовленные таблицы\table_013.csv')
table_013['Год'] = table_013['Год'].astype(int)

### Таблица 014. Удельный вес злокачественных новообразований, выявленных в III стадии, из числа впервые выявленных злокачественных новообразований в России в 2011-2021 гг., %

In [49]:
table_014 = pd.read_excel('2021_Таблица_014_Состояние_онко_помощи_в_РФ.xlsx', header=[0, 1, 2])
table_014

Удельный вес злокачественных новообразований, выявленных в III стадии, из числа впервые выявленных злокачественных новообразований  в России в 2011-2021 гг., %  \
                                                                                                                                 Локализация, нозологическая форма   
                                                                                                                                                Unnamed: 0_level_2   
0                                                                                                                                      Все злокач. новообразования   
1                                                                                                                                                             Губа   
2                                                                                                                                                      Полость рта   
3                                                                                                                                                           Глотка   
4                                                                                                                                                          Пищевод   
5                                                                                                                                                          Желудок   
6                                                                                                                                                  Ободочная кишка   
7                                                                                                                              Прямая кишка, ректосигм. соед, анус   
8                                                                                                                                Печень и внутрипеч. желч. протоки   
9                                                                                                                                             Поджелудочная железа   
10                                                                                                                                                         Гортань   
11                                                                                                                                          Трахея, бронхи, легкое   
12                                                                                                                                         Кости и суставные хрящи   
13                                                                                                                                                   Меланома кожи   
14                                                                                                                                           Кожа (кроме меланомы)   
15                                                                                                                               Соединительная и др. мягкие ткани   
16                                                                                                                                                 Молочная железа   
17                                                                                                                                                     Шейка матки   
18                                                                                                                                                      Тело матки   
19                                                                                                                                                          Яичник   
20                                                                                                                                           Предстательная железа   
21                 

In [50]:
table_014 = table_014.droplevel(0, axis=1) #удаление верхнего уровня индекса
table_014 = table_014.droplevel(0, axis=1)

# переименование столбцов
table_014.rename(columns = {'Unnamed: 0_level_2':'Локализация, нозологическая форма', \
                            'Unnamed: 1_level_2':'Код МКБ 10',\
                           }, inplace = True )

# словарь локализация - код
dict_014 = pd.Series(table_014['Код МКБ 10'].values,index=table_014['Локализация, нозологическая форма']).to_dict()

# переворот таблицы
table_014 = table_014.set_index('Локализация, нозологическая форма') #установление индекса
table_014 = table_014.stack().reset_index()

# переименование колонок
table_014.rename(columns = {'level_1':'Год', \
                            0:'Удельный вес злокачественных новообразований, выявленных в III стадии, из числа впервые выявленных злокачественных новообразований'}, inplace = True)

# удаление лишних строк
table_014 = table_014[table_014['Год'] != 'Код МКБ 10']

# вставка столбца с кодом заболевания
table_014["Код МКБ 10"] = table_014["Локализация, нозологическая форма"].map(dict_014) 
table_014

# замена значения столбца, чтоб было в едином стиле для удобного дальнейшего объединения
table_014['Локализация, нозологическая форма'] =  table_014['Локализация, нозологическая форма']\
                                                   .str.replace('Все злокач. новообразования',\
                                                                'Все злокачественные новообразования')
table_014

Локализация, нозологическая форма   Год  \
1    Все злокачественные новообразования  2011   
2    Все злокачественные новообразования  2012   
3    Все злокачественные новообразования  2013   
4    Все злокачественные новообразования  2014   
5    Все злокачественные новообразования  2015   
..                                   ...   ...   
283                    Щитовидная железа  2017   
284                    Щитовидная железа  2018   
285                    Щитовидная железа  2019   
286                    Щитовидная железа  2020   
287                    Щитовидная железа  2021   

    Удельный вес злокачественных новообразований, выявленных в III стадии, из числа впервые выявленных злокачественных новообразований  \
1                                                                                                                                 21.8   
2                                                                                                                                 21.5   
3                                                                                                                                 21.2   
4                                                                                                                                 20.6   
5                                                                                                                                 20.1   
..                                                                                                                                 ...   
283                                                                                                                               15.9   
284                                                                                                                               14.3   
285                                                                                                                               11.5   
286                                                                                                                                8.1   
287                                                                                                                                5.6   

    Код МКБ 10  
1       С00-96  
2       С00-96  
3       С00-96  
4       С00-96  
5       С00-96  
..         ...  
283        С73  
284        С73  
285        С73  
286        С73  
287        С73  

[264 rows x 4 columns]

In [51]:
# информация о файле
table_014.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 264 entries, 1 to 287
Data columns (total 4 columns):
 #   Column                                                                                                                              Non-Null Count  Dtype 
---  ------                                                                                                                              --------------  ----- 
 0   Локализация, нозологическая форма                                                                                                   264 non-null    object
 1   Год                                                                                                                                 264 non-null    object
 2   Удельный вес злокачественных новообразований, выявленных в III стадии, из числа впервые выявленных злокачественных новообразований  264 non-null    object
 3   Код МКБ 10                                                                                 

Таблица состоит из 264 строк и 4 столбца. Название колонок удобночитаемы. Пропущенных значений нет. Некоторые типы данных необходимо поменять.  
  
Описание данных  
В каждой строке указан удельный вес в процентах злокачественных новообразований, выявленных в III стадии, из числа впервые выявленных злокачественных новообразований в России в 2011-2021 гг..

In [52]:
# перевод типа данных в float
table_014['Удельный вес злокачественных новообразований, выявленных в III стадии, из числа впервые выявленных злокачественных новообразований'] = \
    table_014['Удельный вес злокачественных новообразований, выявленных в III стадии, из числа впервые выявленных злокачественных новообразований'].astype(float)

In [53]:
# сохранение файла в csv
table_014.to_csv(r'C:\Users\Sincerity\Desktop\Проекты\PET- проекты\Дашборд Заболевания\Подготовленные таблицы\table_014.csv')
table_014['Год'] = table_014['Год'].astype(int)

### Таблица 015. Удельный вес злокачественных новообразований, выявленных в запущенной стадии (IV стадия), из числа впервые выявленных злокачественных новообразований в России в 2011-2021 гг., %

In [54]:
table_015 = pd.read_excel('2021_Таблица_015_Состояние_онко_помощи_в_РФ.xlsx', header=[0, 1, 2])
table_015

Таблица 15\nУдельный вес злокачественных новообразований, выявленных в запущенной стадии (IV стадия), из числа впервые выявленных злокачественных новообразований в России в 2011-2021 гг., %  \
                                                                                                                                                               Локализация, нозологическая форма   
                                                                                                                                                                              Unnamed: 0_level_2   
0                                                                                                                                                                    Все злокач. новообразования   
1                                                                                                                                                                                           Губа   
2                                                                                                                                                                                    Полость рта   
3                                                                                                                                                                                         Глотка   
4                                                                                                                                                                                        Пищевод   
5                                                                                                                                                                                        Желудок   
6                                                                                                                                                                                Ободочная кишка   
7                                                                                                                                                            Прямая кишка, ректосигм. соед, анус   
8                                                                                                                                                              Печень и внутрипеч. желч. протоки   
9                                                                                                                                                                           Поджелудочная железа   
10                                                                                                                                                                                       Гортань   
11                                                                                                                                                                        Трахея, бронхи, легкое   
12                                                                                                                                                                       Кости и суставные хрящи   
13                                                                                                                                                                                 Меланома кожи   
14                                                                                                                                                                    Меланома кожи (III−IV ст.)   
15                                                                                                                                                                         Кожа (кроме меланомы)   
16                                                                                                                                                                      Соед. и др. мягкие ткани   
17                                                                                 

In [55]:
table_015 = table_015.droplevel(0, axis=1) #удаление верхнего уровня индекса
table_015 = table_015.droplevel(0, axis=1)

# переименование столбцов
table_015.rename(columns = {'Unnamed: 0_level_2':'Локализация, нозологическая форма', \
                            'Unnamed: 1_level_2':'Код МКБ 10',\
                           }, inplace = True )

# словарь локализация - код
dict_015 = pd.Series(table_015['Код МКБ 10'].values,index=table_015['Локализация, нозологическая форма']).to_dict()

# переворот таблицы
table_015 = table_015.set_index('Локализация, нозологическая форма') #установление индекса
table_015 = table_015.stack().reset_index()

# переименование колонок
table_015.rename(columns = {'level_1':'Год', \
                            0:'Удельный вес злокачественных новообразований, выявленных в запущенной стадии (IV стадия), из числа впервые выявленных злокачественных новообразований'}, inplace = True)

# удаление лишних строк
table_015 = table_015[table_015['Год'] != 'Код МКБ 10']

# вставка столбца с кодом заболевания
table_015["Код МКБ 10"] = table_015["Локализация, нозологическая форма"].map(dict_015) 

# замена значения столбца, чтоб было в едином стиле для удобного дальнейшего объединения
table_015['Локализация, нозологическая форма'] =  table_015['Локализация, нозологическая форма']\
                                                   .str.replace('Соед. и др. мягкие ткани', \
                                                                'Соединительная и др. мягкие ткани')
table_015['Локализация, нозологическая форма'] =  table_015['Локализация, нозологическая форма']\
                                                   .str.replace('Все злокач. новообразования',\
                                                                'Все злокачественные новообразования')

table_015["Код МКБ 10"] = table_015["Код МКБ 10"].str.replace('С46.1.3.7-9; 47.49', 'С47,49')
table_015["Код МКБ 10"] = table_015["Код МКБ 10"].str.replace('С01-09,46.2', 'С01-09')


table_015

Локализация, нозологическая форма   Год  \
1    Все злокачественные новообразования  2011   
2    Все злокачественные новообразования  2012   
3    Все злокачественные новообразования  2013   
4    Все злокачественные новообразования  2014   
5    Все злокачественные новообразования  2015   
..                                   ...   ...   
331       Щитовидная железа (III−IV ст.)  2017   
332       Щитовидная железа (III−IV ст.)  2018   
333       Щитовидная железа (III−IV ст.)  2019   
334       Щитовидная железа (III−IV ст.)  2020   
335       Щитовидная железа (III−IV ст.)  2021   

    Удельный вес злокачественных новообразований, выявленных в запущенной стадии (IV стадия), из числа впервые выявленных злокачественных новообразований  \
1                                                                                                                                                    21.3   
2                                                                                                                                                    21.2   
3                                                                                                                                                    21.1   
4                                                                                                                                                    20.7   
5                                                                                                                                                    20.4   
..                                                                                                                                                    ...   
331                                                                                                                                                  23.2   
332                                                                                                                                                  21.0   
333                                                                                                                                                  17.9   
334                                                                                                                                                  13.6   
335                                                                                                                                                  10.2   

    Код МКБ 10  
1       С00-96  
2       С00-96  
3       С00-96  
4       С00-96  
5       С00-96  
..         ...  
331        С73  
332        С73  
333        С73  
334        С73  
335        С73  

[308 rows x 4 columns]

In [56]:
# информация о файле
table_015.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 308 entries, 1 to 335
Data columns (total 4 columns):
 #   Column                                                                                                                                                 Non-Null Count  Dtype 
---  ------                                                                                                                                                 --------------  ----- 
 0   Локализация, нозологическая форма                                                                                                                      308 non-null    object
 1   Год                                                                                                                                                    308 non-null    object
 2   Удельный вес злокачественных новообразований, выявленных в запущенной стадии (IV стадия), из числа впервые выявленных злокачественных новообразований  308 non-null    object
 

Таблица состоит из 308 строк и 4 столбца. Название колонок удобночитаемы. Пропущенных значений нет, некоторые типы данных надо поменять.
  
Описание данных  
В каждой строке указан удельный вес злокачественных новообразований, выявленных в запущенной стадии (IV стадия), из числа впервые выявленных злокачественных новообразований в России в 2011-2021 гг..

In [57]:
table_015['Удельный вес злокачественных новообразований, выявленных в запущенной стадии (IV стадия), из числа впервые выявленных злокачественных новообразований'] = \
    table_015['Удельный вес злокачественных новообразований, выявленных в запущенной стадии (IV стадия), из числа впервые выявленных злокачественных новообразований'].astype(float)

In [58]:
# сохранение файла в csv
table_015.to_csv(r'C:\Users\Sincerity\Desktop\Проекты\PET- проекты\Дашборд Заболевания\Подготовленные таблицы\table_015.csv')
table_015['Год'] = table_015['Год'].astype(int)

### Таблица 016. Летальность больных в течение года с момента установления диагноза злокачественного новообразования (из числа больных, впервые взятых на учет в предыдущем году) в России в 2011-2021 гг., %

In [59]:
table_016 = pd.read_excel('2021_Таблица_016_Состояние_онко_помощи_в_РФ.xlsx', header=[0, 1, 2], decimal=',', na_values=['-'])
table_016

Таблица 16\nЛетальность больных в течение года с момента установления диагноза злокачественного новообразования (из числа больных, впервые взятых на учет в предыдущем году) в России в 2011-2021 гг.,  %  \
                                                                                                                                                                           Локализация, нозологическая форма   
                                                                                                                                                                                          Unnamed: 0_level_2   
0                                                                                                                                                                          Все злокачествен. новообразования   
1                                                                                                                                                                                                       Губа   
2                                                                                                                                                                                                Полость рта   
3                                                                                                                                                                                                     Глотка   
4                                                                                                                                                                                                    Пищевод   
5                                                                                                                                                                                                    Желудок   
6                                                                                                                                                                                            Ободочная кишка   
7                                                                                                                                                                        Прямая кишка, ректосигм. соед, анус   
8                                                                                                                                                                          Печень и внутрипеч. желч. протоки   
9                                                                                                                                                                                       Поджелудочная железа   
10                                                                                                                                                                                                   Гортань   
11                                                                                                                                                                                    Трахея, бронхи, легкое   
12                                                                                                                                                                                   Кости и суставные хрящи   
13                                                                                                                                                                                             Меланома кожи   
14                                                                                                                                                                                     Кожа (кроме меланомы)   
15                                                                                                                                                                         Соединительная и др. мягкие ткани   
16                                                 

In [60]:
table_016 = table_016.droplevel(0, axis=1) #удаление верхнего уровня индекса
table_016 = table_016.droplevel(0, axis=1)

# переименование столбцов
table_016.rename(columns = {'Unnamed: 0_level_2':'Локализация, нозологическая форма', \
                            'Unnamed: 1_level_2':'Код МКБ 10',\
                           }, inplace = True )

# словарь локализация - код
dict_016 = pd.Series(table_016['Код МКБ 10'].values,index=table_016['Локализация, нозологическая форма']).to_dict()

# переворот таблицы
table_016 = table_016.set_index('Локализация, нозологическая форма') #установление индекса
table_016 = table_016.stack().reset_index()

# переименование колонок
table_016.rename(columns = {'level_1':'Год', \
                            0:'Летальность больных в течение года с момента установления диагноза злокачественного новообразования (из числа больных, впервые взятых на учет в предыдущем году)'}, inplace = True)

# удаление лишних строк
table_016 = table_016[table_016['Год'] != 'Код МКБ 10']

# вставка столбца с кодом заболевания
table_016["Код МКБ 10"] = table_016["Локализация, нозологическая форма"].map(dict_016) 

# замена значения столбца, чтоб было в едином стиле для удобного дальнейшего объединения
table_016['Локализация, нозологическая форма'] =  table_016['Локализация, нозологическая форма']\
                                                   .str.replace('Лимфатическая и кроветворная ткань', 'Лимфатич. и кроветворная ткань')

# замена значения столбца, чтоб было в едином стиле для удобного дальнейшего объединения
table_016['Локализация, нозологическая форма'] =  table_016['Локализация, нозологическая форма']\
                                                   .str.replace('Все злокачествен. новообразования',\
                                                                'Все злокачественные новообразования')

table_016

Локализация, нозологическая форма   Год  \
1    Все злокачественные новообразования  2011   
2    Все злокачественные новообразования  2012   
3    Все злокачественные новообразования  2013   
4    Все злокачественные новообразования  2014   
5    Все злокачественные новообразования  2015   
..                                   ...   ...   
288       Лимфатич. и кроветворная ткань  2017   
289       Лимфатич. и кроветворная ткань  2018   
290       Лимфатич. и кроветворная ткань  2019   
291       Лимфатич. и кроветворная ткань  2020   
292       Лимфатич. и кроветворная ткань  2021   

    Летальность больных в течение года с момента установления диагноза злокачественного новообразования (из числа больных, впервые взятых на учет в предыдущем году)  \
1                                                                                                                                                               27.4   
2                                                                                                                                                               26.1   
3                                                                                                                                                               25.3   
4                                                                                                                                                               24.8   
5                                                                                                                                                               23.6   
..                                                                                                                                                               ...   
288                                                                                                                                                             21.6   
289                                                                                                                                                             22.3   
290                                                                                                                                                             21.7   
291                                                                                                                                                             21.6   
292                                                                                                                                                             20.7   

    Код МКБ 10  
1       С00-96  
2       С00-96  
3       С00-96  
4       С00-96  
5       С00-96  
..         ...  
288     C81-96  
289     C81-96  
290     C81-96  
291     C81-96  
292     C81-96  

[268 rows x 4 columns]

In [61]:
# информация о файле
table_016.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 268 entries, 1 to 292
Data columns (total 4 columns):
 #   Column                                                                                                                                                            Non-Null Count  Dtype 
---  ------                                                                                                                                                            --------------  ----- 
 0   Локализация, нозологическая форма                                                                                                                                 268 non-null    object
 1   Год                                                                                                                                                               268 non-null    object
 2   Летальность больных в течение года с момента установления диагноза злокачественного новообразования (из числа больных, впервые взят

Таблица состоит из 268 строк и 4 столбцов. Название колонок удобночитаемы. Пропущенных значений нет, данные соответствуют типам данных.
  
Описание данных  
В каждой строке указан летальность больных в процентах в течение года с момента установления диагноза злокачественного новообразования (из числа больных, впервые взятых на учет в предыдущем году) в России в 2011-2021 гг..

In [62]:
table_016['Летальность больных в течение года с момента установления диагноза злокачественного новообразования (из числа больных, впервые взятых на учет в предыдущем году)'] = \
    table_016['Летальность больных в течение года с момента установления диагноза злокачественного новообразования (из числа больных, впервые взятых на учет в предыдущем году)'].astype(float)

In [63]:
# сохранение файла в csv
table_016.to_csv(r'C:\Users\Sincerity\Desktop\Проекты\PET- проекты\Дашборд Заболевания\Подготовленные таблицы\table_016.csv')
table_016['Год'] = table_016['Год'].astype(int)

### Таблица 017. Основные показатели состояния онкологической помощи детскому населению (0-14 лет) России в 2011-2021 гг.

In [64]:
table_017 = pd.read_excel('2021_Таблица_017_Состояние_онко_помощи_в_РФ.xlsx', header=[0, 1, 2, 3, 4, 5])
table_017

Таблица 17  \
   Основные показатели состояния онкологической помощи детскому населению (0-14 лет) России в 2011-2021 гг.   
                                                                                                       Годы   
                                                                                         Unnamed: 0_level_3   
                                                                                         Unnamed: 0_level_4   
                                                                                         Unnamed: 0_level_5   
0                                                                                                      2011   
1                                                                                                      2012   
2                                                                                                      2013   
3                                                                                                      2014   
4                                                                                                      2015   
5                                                                                                      2016   
6                                                                                                      2017   
7                                                                                                      2018   
8                                                                                                      2019   
9                                                                                                      2020   
10                                                                                                     2021   
11                                                              *использована численность населения 2020 г.   

                                                                           \
                                                                            
   Абсолют- ное число больных с впервые в жизни установ- ленным диагнозом   
                                                       Unnamed: 1_level_3   
                                                       Unnamed: 1_level_4   
                                                       Unnamed: 1_level_5   
0                                                                  2621.0   
1                                                                  2682.0   
2                                                                  2819.0   
3                                                                  3003.0   
4                                                                  3102.0   
5                                                                  3220.0   
6                                                                  3279.0   
7                                                                  3214.0   
8                                                                  3115.0   
9                                                                  3110.0   
10                                                                 2928.0   
11                                                                    NaN   

                                                               \
                                                                
   Из числа больных с впервые в жизни установленным диагнозом   
                                           Unnamed: 2_level_3   
                                      выявле- но актив- но, %   
                                           Unnamed: 2_level_5   
0                                                         3.7   
1                                                         3.0   
2                                                         5.4   
3                                                         4.5   
4                                                         4.9

Приведем таблицу к удобному виду: сделаем один уровень заголовков столбцов и таблицу транспонируем.

In [65]:
# загрузка данных
table_017_2v = pd.read_excel('2021_Таблица_017_Состояние_онко_помощи_в_РФ.xlsx', header=[0, 1, 2, 3, 4, 5])
table_017_2v = table_017_2v.droplevel(0, axis=1) #удаление верхнего уровня индекса
table_017_2v = table_017_2v.droplevel(0, axis=1)
table_017_2v = table_017_2v.droplevel(0, axis=1)
table_017_2v = table_017_2v.droplevel(0, axis=1)
table_017_2v = table_017_2v.droplevel(0, axis=1)

table_017_2v = table_017_2v.replace('88,4*', '88.4')

table_017_2v.rename(columns = {'Unnamed: 0_level_5':'Показатели',\
                             'Unnamed: 1_level_5':'Абсолютное число больных с впервые в жизни установленным диагнозом',\
                             'Unnamed: 2_level_5':'Выявлено активно, % из числа больных с впервые в жизни установленным диагнозом',\
                             'Unnamed: 3_level_5':'Диагноз подтвержден морфологически, % из числа больных с впервые в жизни установленным диагнозом',\
                             'I-II':'Имели I-II стадию заболевания, % из числа больных с впервые в жизни установленным диагнозом',\
                             'III':'Имели III стадию заболевания, % из числа больных с впервые в жизни установленным диагнозом',\
                             'IV':'Имели IV стадию заболевания, % из числа больных с впервые в жизни установленным диагнозом',\
                             'не ус- танов- лена':'Неустановленная стадия, % из числа больных с впервые в жизни установленным диагнозом',\
                             'Unnamed: 8_level_5':'Летальность на первом году с момента установления диагноза, %',\
                             'Unnamed: 9_level_5':'Летальность, %',\
                             'Unnamed: 10_level_5':'Находились под наблюдением на конец года, абсолютное число',\
                             'Unnamed: 11_level_5':'Находились под наблюдением на конец года, на 100 тыс. детск. населения',\
                             'Unnamed: 12_level_5':'Находились под наблюдением 5 и более лет на конец года, абсолютно число',\
                             'Unnamed: 13_level_5':'Находились под наблюдением 5 и более лет на конец года, %',\
                             'Unnamed: 14_level_5':'Индекс накопления контингентов, %'\
                              }, inplace = True)
table_017_2v = table_017_2v.drop(index = 11) # удаление ремарки
table_017_2v

Показатели  \
0        2011   
1        2012   
2        2013   
3        2014   
4        2015   
5        2016   
6        2017   
7        2018   
8        2019   
9        2020   
10       2021   

    Абсолютное число больных с впервые в жизни установленным диагнозом  \
0                                                               2621.0   
1                                                               2682.0   
2                                                               2819.0   
3                                                               3003.0   
4                                                               3102.0   
5                                                               3220.0   
6                                                               3279.0   
7                                                               3214.0   
8                                                               3115.0   
9                                                               3110.0   
10                                                              2928.0   

    Выявлено активно, % из числа больных с впервые в жизни установленным диагнозом  \
0                                                                              3.7   
1                                                                              3.0   
2                                                                              5.4   
3                                                                              4.5   
4                                                                              4.9   
5                                                                              5.0   
6                                                                              5.2   
7                                                                              5.6   
8                                                                              4.0   
9                                                                              5.9   
10                                                                             5.8   

    Диагноз подтвержден морфологически, % из числа больных с впервые в жизни установленным диагнозом  \
0                                                                                               92.4   
1                                                                                               93.2   
2                                                                                               89.6   
3                                                                                               89.6   
4                                                                                               92.6   
5                                                                                               93.4   
6                                                                                               95.5   
7                                                                                               95.1   
8                                                                                               95.5   
9                                                                                               95.2   
10                                                                                              95.8   

    Имели I-II стадию заболевания, % из числа больных с впервые в жизни установленным диагнозом  \
0                                                                                          27.0   
1                                                                                          22.9   
2                                                                                          23.1   
3                                                                                          22.9   
4                                                                                          21.1   
5                                

In [66]:
# информация о файле
table_017_2v.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 15 columns):
 #   Column                                                                                            Non-Null Count  Dtype  
---  ------                                                                                            --------------  -----  
 0   Показатели                                                                                        11 non-null     object 
 1   Абсолютное число больных с впервые в жизни установленным диагнозом                                11 non-null     float64
 2   Выявлено активно, % из числа больных с впервые в жизни установленным диагнозом                    11 non-null     float64
 3   Диагноз подтвержден морфологически, % из числа больных с впервые в жизни установленным диагнозом  11 non-null     float64
 4   Имели I-II стадию заболевания, % из числа больных с впервые в жизни установленным диагнозом       11 non-null     float64
 5   Име

Таблица состоит из 154 строк и 3 столбца. Название колонок удобночитаемы. Пропущенных значений нет. Необходимо поменять некоторые типы столбцов.  
  
Описание данных  
В каждой строке указан основные показатели состояния онкологической помощи детскому населению (0-14 лет) России в 2011-2021 гг.

In [67]:
table_017_2v.to_csv(r'C:\Users\Sincerity\Desktop\Проекты\PET- проекты\Дашборд Заболевания\Подготовленные таблицы\table_017_2v.csv')


In [68]:
table_017_2v_with_date = table_017_2v.copy()
table_017_2v_with_date['Показатели'] = pd.to_datetime(table_017_2v_with_date['Показатели'], format='%Y')#.dt.year
table_017_2v_with_date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 15 columns):
 #   Column                                                                                            Non-Null Count  Dtype         
---  ------                                                                                            --------------  -----         
 0   Показатели                                                                                        11 non-null     datetime64[ns]
 1   Абсолютное число больных с впервые в жизни установленным диагнозом                                11 non-null     float64       
 2   Выявлено активно, % из числа больных с впервые в жизни установленным диагнозом                    11 non-null     float64       
 3   Диагноз подтвержден морфологически, % из числа больных с впервые в жизни установленным диагнозом  11 non-null     float64       
 4   Имели I-II стадию заболевания, % из числа больных с впервые в жизни установленным диагно

In [69]:
table_017_2v_with_date.to_csv(r'C:\Users\Sincerity\Desktop\Проекты\PET- проекты\Дашборд Заболевания\Подготовленные таблицы\table_017_2v_with_date.csv')


### Таблица 055. Сведения о злокачественных новообразованиях, лечение которых не проводилось по причине отказа пациента и противопоказаний к проведению лечения в России в 2011-2021 гг. 

In [70]:
# загрузка данных
table_055 = pd.read_excel('2021_Таблица_055_Состояние_онко_помощи_в_РФ.xlsx', header=[0, 1, 2])
table_055

Сведения о злокачественных новообразованиях, лечение которых не проводилось по причине отказа пациента и противопоказаний к проведению лечения в России в 2011-2021 гг.              Таблица 55             \
                                                                                                                                                                                                  Показатели   
                                                                                                                                                                                          Unnamed: 0_level_2   
0                                            Доля злокачественных новообразований, лечение которых не проводилось по причине отказа пациента, от числа впервые выявленных злокачественных новообразований, %   
1                                    Доля злокачественных новообразований в I-II стадии  из числа\nзлокачественных новообразований, радикальное лечение которых не проводилось по причине отказа пациента, %   
2                                         Доля злокачественных новообразований, лечение которых не проводилось по причине противопоказаний, от числа  впервые выявленных злокачественного новообразований, %   
3                                    Доля злокачественных новообразований в I-II стадии из числа злокачественных новообразований, радикальное лечение\nкоторых не проводилось по причине противопоказаний, %   

                                                                     
   Годы                                                              
   2011  2012  2013  2014  2015  2016  2017  2018  2019  2020  2021  
0   2.9   2.6   2.4   2.2   2.2   2.0   1.8   1.8   1.6   1.5   1.4  
1  40.9  42.2  44.3  46.0  42.1  46.8  50.3  48.5  53.0  49.3  51.3  
2   8.8   9.3   8.6   7.4   7.1   6.7   6.8   6.9   6.4   6.0   6.1  
3  31.9  30.3  30.6  34.3  34.0  35.9  36.3  38.8  43.0  43.3  44.5

In [71]:
table_055_2v = table_055.droplevel(0, axis=1) #удаление верхнего уровня индекса
table_055_2v = table_055_2v.droplevel(0, axis=1)

# переименование столбцов
table_055_2v.rename(columns = {'Unnamed: 0_level_2':'Наименование показателя'}, inplace = True )
table_055_2v = table_055_2v.set_index('Наименование показателя') #установление индекса

table_055_2v = table_055_2v.T
table_055_2v

Наименование показателя  Доля злокачественных новообразований, лечение которых не проводилось по причине отказа пациента, от числа впервые выявленных злокачественных новообразований, %  \
2011                                                                                                                                                                                 2.9   
2012                                                                                                                                                                                 2.6   
2013                                                                                                                                                                                 2.4   
2014                                                                                                                                                                                 2.2   
2015                                                                                                                                                                                 2.2   
2016                                                                                                                                                                                 2.0   
2017                                                                                                                                                                                 1.8   
2018                                                                                                                                                                                 1.8   
2019                                                                                                                                                                                 1.6   
2020                                                                                                                                                                                 1.5   
2021                                                                                                                                                                                 1.4   

Наименование показателя  Доля злокачественных новообразований в I-II стадии  из числа\nзлокачественных новообразований, радикальное лечение которых не проводилось по причине отказа пациента, %  \
2011                                                                                                                                                                                        40.9   
2012                                                                                                                                                                                        42.2   
2013                                                                                                                                                                                        44.3   
2014                                                                                                                                                                                        46.0   
2015                                                                                                                                                                                        42.1   
2016                                                                                                                                                                                        46.8   
2017                                                                                                                                                                                        50.3   
2018                                                                                                                                                                           

In [72]:
# информация о файле
table_055_2v.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11 entries, 2011 to 2021
Data columns (total 4 columns):
 #   Column                                                                                                                                                                  Non-Null Count  Dtype  
---  ------                                                                                                                                                                  --------------  -----  
 0   Доля злокачественных новообразований, лечение которых не проводилось по причине отказа пациента, от числа впервые выявленных злокачественных новообразований, %         11 non-null     float64
 1   Доля злокачественных новообразований в I-II стадии  из числа
злокачественных новообразований, радикальное лечение которых не проводилось по причине отказа пациента, %  11 non-null     float64
 2   Доля злокачественных новообразований, лечение которых не проводилось по причине противопоказаний, от числ

Таблица состоит из 11 строк и 4 столбцов. Название колонок удобночитаемы. Пропущенных значений нет. Тип данных в колонке 2 необходимо поменять.  
  
Описание данных  
В каждой строке указан сведения о злокачественных новообразованиях, лечение которых не проводилось по причине отказа пациента и противопоказаний к проведению лечения в России в 2011-2021 гг. 

In [73]:
# сохранение файла в csv
table_055_2v.to_csv(r'C:\Users\Sincerity\Desktop\Проекты\PET- проекты\Дашборд Заболевания\Подготовленные таблицы\table_055_2v.csv')

### Таблица 056. Сведения о лечении детей (0-14 лет) со злокачественными новообразованиями в России в 2011-2021 г.

In [74]:
table_056 = pd.read_excel('2021_Таблица_056_Состояние_онко_помощи_в_РФ.xlsx', header=[0, 1, 2])
table_056

Таблица 56\nСведения о лечении детей (0-14 лет) со злокачественными новообразованиями в России в 2011-2021 г.  \
                                                                                                            Годы   
                                                                                              Unnamed: 0_level_2   
0                                                                                                           2011   
1                                                                                                           2012   
2                                                                                                           2013   
3                                                                                                           2014   
4                                                                                                           2015   
5                                                                                                           2016   
6                                                                                                           2017   
7                                                                                                           2018   
8                                                                                                           2019   
9                                                                                                           2020   
10                                                                                                          2021   

                                                     \
   Число больных, закончивших\nрадикальное  лечение   
                                   абсолютное число   
0                                              1325   
1                                              1283   
2                                              1316   
3                                              1343   
4                                              1410   
5                                              1402   
6                                              1434   
7                                              1304   
8                                              1255   
9                                              1220   
10                                             1214   

                                  \
                                   
   на 100 впервые взятых на учет   
0                           50.3   
1                           47.8   
2                           46.4   
3                           44.5   
4                           45.1   
5                           43.3   
6                           43.5   
7                           40.3   
8                           40.2   
9                           39.2   
10                          41.5   

                                                                               \
   Лечение проведено с использованием методов (из числа закончивших лечение):   
                                                     только хирургического, %   
0                                                                        23.2   
1                                                                        25.1   
2                                                                        24.5   
3                                                                        24.7   
4                                                                        27.1   
5                                                                        24.8   
6                                                                        25.7   
7                                                                        24.5   
8                                                                        31.3   
9                                                                        27.8   
10                                               

In [75]:
# загрузка данных
table_056_2v = pd.read_excel('2021_Таблица_056_Состояние_онко_помощи_в_РФ.xlsx', header=[0, 1, 2])
table_056_2v = table_056_2v.droplevel(0, axis=1) #удаление верхнего уровня индекса
table_056_2v = table_056_2v.droplevel(0, axis=1)
table_056_2v.rename(columns = {'Unnamed: 0_level_2':'Показатели',\
                             'абсолютное число':'Число больных, закончивших nрадикальное лечение, абс. число',\
                             'на 100 впервые взятых на учет':'Число больных, закончивших nрадикальное лечениена 100 впервые взятых на учет, %',\
                             'только хирургического, %':'Проведено только хирургическое лечение (из числа закончивших лечение), %',\
                             'только лекарственного, %':'Проведено только лекарственное лечение (из числа закончивших лечение), %',\
                             'комбинированного или комплексного, %':'Проведено комбинированное или комплексное лечение (из числа закончивших лечение), %',\
                             'химиолучевого, %':'Проведено только химиолучевое лечение (из числа закончивших лечение), %',\
                              }, inplace = True)
table_056_2v

Показатели  Число больных, закончивших nрадикальное лечение, абс. число  \
0         2011                                                         1325   
1         2012                                                         1283   
2         2013                                                         1316   
3         2014                                                         1343   
4         2015                                                         1410   
5         2016                                                         1402   
6         2017                                                         1434   
7         2018                                                         1304   
8         2019                                                         1255   
9         2020                                                         1220   
10        2021                                                         1214   

    Число больных, закончивших nрадикальное лечениена 100 впервые взятых на учет, %  \
0                                                                              50.3   
1                                                                              47.8   
2                                                                              46.4   
3                                                                              44.5   
4                                                                              45.1   
5                                                                              43.3   
6                                                                              43.5   
7                                                                              40.3   
8                                                                              40.2   
9                                                                              39.2   
10                                                                             41.5   

    Проведено только хирургическое лечение (из числа закончивших лечение), %  \
0                                                                       23.2   
1                                                                       25.1   
2                                                                       24.5   
3                                                                       24.7   
4                                                                       27.1   
5                                                                       24.8   
6                                                                       25.7   
7                                                                       24.5   
8                                                                       31.3   
9                                                                       27.8   
10                                                                      29.0   

    только лучевого, %  \
0                  1.3   
1                  0.3   
2                  0.5   
3                  1.5   
4                  0.6   
5                  0.6   
6                  0.3   
7                  1.0   
8                  1.0   
9                  1.2   
10                 1.1   

    Проведено только лекарственное лечение (из числа закончивших лечение), %  \
0                                                                       37.6   
1                                                                       40.6   
2                                                                       41.3   
3                                                                       39.0   
4                                                                       42.6   
5                                                                       42.4   
6                                                                       44.1   
7                                                                       40.6   
8               

In [76]:
# информация о файле
table_056_2v.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 8 columns):
 #   Column                                                                               Non-Null Count  Dtype  
---  ------                                                                               --------------  -----  
 0   Показатели                                                                           11 non-null     int64  
 1   Число больных, закончивших nрадикальное лечение, абс. число                          11 non-null     int64  
 2   Число больных, закончивших nрадикальное лечениена 100 впервые взятых на учет, %      11 non-null     float64
 3   Проведено только хирургическое лечение (из числа закончивших лечение), %             11 non-null     float64
 4   только лучевого, %                                                                   11 non-null     float64
 5   Проведено только лекарственное лечение (из числа закончивших лечение), %             11 non-nul

Таблица состоит из 11 строк и 8 столбцов. Название колонок удобночитаемы. Пропущенных значений нет, данные соответствуют типам данных.
  
Описание данных  
В каждой строке указанs cведения о лечении детей (0-14 лет) со злокачественными новообразованиями в России в 2011-2021 г.

In [77]:
# сохранение файла в csv
table_056_2v.to_csv(r'C:\Users\Sincerity\Desktop\Проекты\PET- проекты\Дашборд Заболевания\Подготовленные таблицы\table_056_2v.csv')

## Объединение таблиц

### Таблица 1

Для того, чтобы удобнее было пользоваться таблицами при визуализации, объединим похожие таблицы в одну.

In [78]:
join_table_1 = table_005.merge(table_006, on=['Локализация, нозологическая форма', 'Год', 'Код МКБ 10'], how = 'outer')
join_table_1 = join_table_1.merge(table_007, on=['Локализация, нозологическая форма', 'Год', 'Код МКБ 10'], how = 'outer')
join_table_1 = join_table_1.merge(table_008, on=['Локализация, нозологическая форма', 'Год', 'Код МКБ 10'], how = 'outer')
join_table_1 = join_table_1.merge(table_009, on=['Локализация, нозологическая форма', 'Год', 'Код МКБ 10'], how = 'outer')
join_table_1 = join_table_1.merge(table_010, on=['Локализация, нозологическая форма', 'Год', 'Код МКБ 10'], how = 'outer')
join_table_1 = join_table_1.merge(table_013, on=['Локализация, нозологическая форма', 'Год', 'Код МКБ 10'], how = 'outer')
join_table_1 = join_table_1.merge(table_014, on=['Локализация, нозологическая форма', 'Год', 'Код МКБ 10'], how = 'outer')
join_table_1 = join_table_1.merge(table_015, on=['Локализация, нозологическая форма', 'Год', 'Код МКБ 10'], how = 'outer')
join_table_1 = join_table_1.merge(table_016, on=['Локализация, нозологическая форма', 'Год', 'Код МКБ 10'], how = 'outer')
join_table_1

Локализация, нозологическая форма   Год  \
0    Все злокачественные новообразования  2011   
1    Все злокачественные новообразования  2012   
2    Все злокачественные новообразования  2013   
3    Все злокачественные новообразования  2014   
4    Все злокачественные новообразования  2015   
..                                   ...   ...   
347       Щитовидная железа (III−IV ст.)  2017   
348       Щитовидная железа (III−IV ст.)  2018   
349       Щитовидная железа (III−IV ст.)  2019   
350       Щитовидная железа (III−IV ст.)  2020   
351       Щитовидная железа (III−IV ст.)  2021   

     Численность контингента больных на 100 тыс. населения Код МКБ 10  \
0                                                   2029.0     С00-96   
1                                                   2091.9     С00-96   
2                                                   2159.4     С00-96   
3                                                   2252.4     С00-96   
4                                                   2325.2     С00-96   
..                                                     ...        ...   
347                                                    NaN        С73   
348                                                    NaN        С73   
349                                                    NaN        С73   
350                                                    NaN        С73   
351                                                    NaN        С73   

     Доля больных, состоявших на учете в онкологических учреждениях России 5 лет и более с момента установления диагноза злокачественного новообразования, от числа состоявших на учете на конец отчетного года  \
0                                                                                                                                                                                                          51.3   
1                                                                                                                                                                                                          51.1   
2                                                                                                                                                                                                          51.7   
3                                                                                                                                                                                                          52.4   
4                                                                                                                                                                                                          52.9   
..                                                                                                                                                                                                          ...   
347                                                                                                                                                                                                         NaN   
348                                                                                                                                                                                                         NaN   
349                                                                                                                                                                                                         NaN   
350                                                                                                                                                                                                         NaN   
351                                                                                                                                                                                                         NaN 

In [79]:
join_table_1['Доля больных, состоявших на учете в онкологических учреждениях России 5 лет и более с момента становления диагноза злокачественного новообразования, от числа состоявших на учете на конец отчетного года 5 лет назад'].describe()

count    209.000000
mean      63.861722
std       10.343893
min       35.200000
25%       58.000000
50%       64.900000
75%       70.400000
max       86.300000
Name: Доля больных, состоявших на учете в онкологических учреждениях России 5 лет и более с момента становления диагноза злокачественного новообразования, от числа состоявших на учете на конец отчетного года 5 лет назад, dtype: float64

In [80]:
join_table_1['Локализация, нозологическая форма (с кодом МКБ 10)'] = join_table_1['Локализация, нозологическая форма'].map(str) +\
                                                                    ' (' + \
                                                                    join_table_1['Код МКБ 10'] + \
                                                                    ')'

In [81]:
join_table_1

Локализация, нозологическая форма   Год  \
0    Все злокачественные новообразования  2011   
1    Все злокачественные новообразования  2012   
2    Все злокачественные новообразования  2013   
3    Все злокачественные новообразования  2014   
4    Все злокачественные новообразования  2015   
..                                   ...   ...   
347       Щитовидная железа (III−IV ст.)  2017   
348       Щитовидная железа (III−IV ст.)  2018   
349       Щитовидная железа (III−IV ст.)  2019   
350       Щитовидная железа (III−IV ст.)  2020   
351       Щитовидная железа (III−IV ст.)  2021   

     Численность контингента больных на 100 тыс. населения Код МКБ 10  \
0                                                   2029.0     С00-96   
1                                                   2091.9     С00-96   
2                                                   2159.4     С00-96   
3                                                   2252.4     С00-96   
4                                                   2325.2     С00-96   
..                                                     ...        ...   
347                                                    NaN        С73   
348                                                    NaN        С73   
349                                                    NaN        С73   
350                                                    NaN        С73   
351                                                    NaN        С73   

     Доля больных, состоявших на учете в онкологических учреждениях России 5 лет и более с момента установления диагноза злокачественного новообразования, от числа состоявших на учете на конец отчетного года  \
0                                                                                                                                                                                                          51.3   
1                                                                                                                                                                                                          51.1   
2                                                                                                                                                                                                          51.7   
3                                                                                                                                                                                                          52.4   
4                                                                                                                                                                                                          52.9   
..                                                                                                                                                                                                          ...   
347                                                                                                                                                                                                         NaN   
348                                                                                                                                                                                                         NaN   
349                                                                                                                                                                                                         NaN   
350                                                                                                                                                                                                         NaN   
351                                                                                                                                                                                                         NaN 

In [82]:
join_table_1['Год'].unique()

array([2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021])

In [83]:
join_table_1['Код МКБ 10'].unique()

array(['С00-96', 'С00', 'С01-09', 'С10-13', 'С15', 'С16', 'С18', 'С19-21',
       'С22', 'С25', 'С32', 'С33,34', 'С40,41', 'С43', 'С44', 'С47,49',
       'С50', 'С53', 'С54', 'С56', 'С61', 'С64', 'С67', 'С73', 'C81-96',
       'С01-14', 'С 40,41,47,49'], dtype=object)

In [84]:
join_table_1['Локализация, нозологическая форма'].unique()

array(['Все злокачественные новообразования', 'Губа', 'Полость рта',
       'Глотка', 'Пищевод', 'Желудок', 'Ободочная кишка',
       'Прямая кишка, ректосигм. соед, анус',
       'Печень и внутрипеч. желч. протоки', 'Поджелудочная железа',
       'Гортань', 'Трахея, бронхи, легкое', 'Кости и суставные хрящи',
       'Меланома кожи', 'Кожа (кроме меланомы)',
       'Соединительная и др. мягкие ткани', 'Молочная железа',
       'Шейка матки', 'Тело матки', 'Яичник', 'Предстательная железа',
       'Почка', 'Мочевой пузырь', 'Щитовидная железа',
       'Лимфатич. и кроветворная ткань', 'Полость рта и глотка',
       'Кости и мягкие ткани', 'Печень и внутрипеч. желч. прот.',
       'Меланома кожи (III−IV ст.)', 'Молочная железа (III−IV ст.)',
       'Шейка матки (III−IV ст.)', 'Щитовидная железа (III−IV ст.)'],
      dtype=object)

In [85]:
join_table_1['Локализация, нозологическая форма (с кодом МКБ 10)'].unique()

array(['Все злокачественные новообразования (С00-96)', 'Губа (С00)',
       'Полость рта (С01-09)', 'Глотка (С10-13)', 'Пищевод (С15)',
       'Желудок (С16)', 'Ободочная кишка (С18)',
       'Прямая кишка, ректосигм. соед, анус (С19-21)',
       'Печень и внутрипеч. желч. протоки (С22)',
       'Поджелудочная железа (С25)', 'Гортань (С32)',
       'Трахея, бронхи, легкое (С33,34)',
       'Кости и суставные хрящи (С40,41)', 'Меланома кожи (С43)',
       'Кожа (кроме меланомы) (С44)',
       'Соединительная и др. мягкие ткани (С47,49)',
       'Молочная железа (С50)', 'Шейка матки (С53)', 'Тело матки (С54)',
       'Яичник (С56)', 'Предстательная железа (С61)', 'Почка (С64)',
       'Мочевой пузырь (С67)', 'Щитовидная железа (С73)',
       'Лимфатич. и кроветворная ткань (C81-96)',
       'Полость рта и глотка (С01-14)',
       'Кости и мягкие ткани (С 40,41,47,49)',
       'Печень и внутрипеч. желч. прот. (С22)',
       'Меланома кожи (III−IV ст.) (С43)',
       'Молочная железа (III−

In [86]:
join_table_1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 352 entries, 0 to 351
Data columns (total 14 columns):
 #   Column                                                                                                                                                                                                                 Non-Null Count  Dtype  
---  ------                                                                                                                                                                                                                 --------------  -----  
 0   Локализация, нозологическая форма                                                                                                                                                                                      352 non-null    object 
 1   Год                                                                                                                                                           

In [87]:
# проверка не повторяются ли коды и названия
dict = pd.Series(join_table_1['Код МКБ 10'].values,index = join_table_1['Локализация, нозологическая форма']).to_dict()
dict

{'Все злокачественные новообразования': 'С00-96',
 'Губа': 'С00',
 'Полость рта': 'С01-09',
 'Глотка': 'С10-13',
 'Пищевод': 'С15',
 'Желудок': 'С16',
 'Ободочная кишка': 'С18',
 'Прямая кишка, ректосигм. соед, анус': 'С19-21',
 'Печень и внутрипеч. желч. протоки': 'С22',
 'Поджелудочная железа': 'С25',
 'Гортань': 'С32',
 'Трахея, бронхи, легкое': 'С33,34',
 'Кости и суставные хрящи': 'С40,41',
 'Меланома кожи': 'С43',
 'Кожа (кроме меланомы)': 'С44',
 'Соединительная и др. мягкие ткани': 'С47,49',
 'Молочная железа': 'С50',
 'Шейка матки': 'С53',
 'Тело матки': 'С54',
 'Яичник': 'С56',
 'Предстательная железа': 'С61',
 'Почка': 'С64',
 'Мочевой пузырь': 'С67',
 'Щитовидная железа': 'С73',
 'Лимфатич. и кроветворная ткань': 'C81-96',
 'Полость рта и глотка': 'С01-14',
 'Кости и мягкие ткани': 'С 40,41,47,49',
 'Печень и внутрипеч. желч. прот.': 'С22',
 'Меланома кожи (III−IV ст.)': 'С43',
 'Молочная железа (III−IV ст.)': 'С50',
 'Шейка матки (III−IV ст.)': 'С53',
 'Щитовидная железа (

In [88]:
join_table_1.to_csv(r'C:\Users\Sincerity\Desktop\Проекты\PET- проекты\Дашборд Заболевания\Подготовленные таблицы\join_table_1.csv')

In [89]:
join_table_1_2v = join_table_1.copy()
join_table_1_2v['Год'] = pd.to_datetime(join_table_1_2v['Год'], format='%Y')#.dt.year
join_table_1_2v.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 352 entries, 0 to 351
Data columns (total 14 columns):
 #   Column                                                                                                                                                                                                                 Non-Null Count  Dtype         
---  ------                                                                                                                                                                                                                 --------------  -----         
 0   Локализация, нозологическая форма                                                                                                                                                                                      352 non-null    object        
 1   Год                                                                                                                                      

In [90]:
join_table_1_2v.to_csv(r'C:\Users\Sincerity\Desktop\Проекты\PET- проекты\Дашборд Заболевания\Подготовленные таблицы\join_table_1_2v.csv')

## Выводы

Таблицы приведены в удобный вид, удалены лишние строки, заменены названия в колонках и строках в единый вид. Таблицы 005-010, 013-016 объединены в одну таблицы с различными показателяит по локализациям. Остальные таблицы обработаны по отдельности.